rtl/candidates/a6_lossless_aer_codec/a6_codec_encoder.sv
rtl/candidates/a6_lossless_aer_codec/a6_codec_decoder.sv
rtl/candidates/a6_lossless_aer_codec/a6_lossless_aer_codec_top.sv
tb/clean/aer_bench_if.sv
rtl/candidates/a6_lossless_aer_codec/a6_candidate_replacement.sv
tb/clean/aer_clean_assertions.sv
tb/clean/aer_clean_tb.sv

