rtl/common/aer_pkg.sv
rtl/baseline/fixed_priority_arbiter.sv
rtl/baseline/aer_tx.sv
rtl/baseline/aer_rx.sv
rtl/baseline/aer_baseline_core.sv
rtl/baseline/aer_dut.sv
rtl/experiments/a3_bubble_free/a3_bubble_free_tx.sv
rtl/experiments/a3_bubble_free/a3_bubble_free_core.sv
rtl/experiments/a3_bubble_free/a3_bubble_free_dut.sv
tests/a3/a3_bubble_free_compare_tb.sv
