rtl/candidates/a7_event_triggered_ddr_burst_link_w4/a7_w4_icg_boundary.sv
rtl/candidates/a7_event_triggered_ddr_burst_link_w4/a7_w4_ddr_tx.sv
rtl/candidates/a7_event_triggered_ddr_burst_link_w4/a7_w4_ddr_rx.sv
rtl/candidates/a7_event_triggered_ddr_burst_link_w4/a7_event_triggered_ddr_burst_link_w4.sv
tests/a7_event_triggered_ddr_burst_link_w4/a7_w4_structural_compare.sv
tests/a7_event_triggered_ddr_burst_link_w4/a7_w4_structural_compare_tb.sv
