+incdir+rtl/technology/p6
+define+W2_P6_TECH_GENERIC
rtl/candidates/a7_p6_exact_pair_endpoint/a7_p6_pair_launch.sv
rtl/candidates/a7_p6_exact_pair_endpoint/a7_p6_pair_observer.sv
rtl/technology/p6/w2_p6_clock_boundary.sv
rtl/technology/p6/w2_p6_posedge_capture.sv
rtl/technology/p6/w2_p6_negedge_capture.sv
rtl/technology/p6/w2_p6_pair_tx_tech.sv
rtl/technology/p6/w2_p6_pair_rx_tech.sv
rtl/technology/p6/w2_p6_exact_pair_endpoint_tech.sv
