from __future__ import annotations

import copy
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[2]
FLOW = ROOT / "physical/k2_endpoint_vectorless/vectorless.py"
SPEC = importlib.util.spec_from_file_location("k2_endpoint_vectorless", FLOW)
assert SPEC and SPEC.loader
vectorless = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(vectorless)


def power_report(top: str, *, activity: str = "N.A.", user: str = "N.A.",
                 sequential: str = "0.200000", primary: str = "0.200000") -> bytes:
    return f"""Generated by:           Genus(TM) Synthesis Solution
Instance: /{top}
* User-Defined Activity : {user}
* Activity File: {activity}
* Sequential Element Activity: {sequential}
* Primary Input Activity: {primary}
Power Unit: W
    Category         Leakage     Internal    Switching        Total
    Subtotal     1.00000e-09  1.00000e-06  1.00000e-06  2.00100e-06
""".encode()


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(vectorless.canonical(value))


def indexed_manifest(evidence_root: Path, rows: list[dict] | None = None) -> Path:
    contract = vectorless.expected_contract()
    registry = vectorless.validate_contract(ROOT, contract)
    document = {
        "schema": "k2_endpoint_vectorless_evidence_v2",
        "evidence_class": contract["evidence_class"],
        "candidate_order": contract["candidate_order"],
        "comparability_policy": contract["comparability_policy"],
        "bindings": vectorless.contract_identity(ROOT, contract, registry),
        "rows": rows if rows is not None else [],
    }
    path = evidence_root / "vectorless-evidence.json"
    write_json(path, document)
    return path


class VectorlessContractTest(unittest.TestCase):
    def test_contract_reuses_native_runner_and_exact_three_endpoints(self) -> None:
        contract = vectorless.expected_contract()
        registry = vectorless.validate_contract(ROOT, contract)
        self.assertEqual(contract["schema"], "k2_endpoint_vectorless_contract_v2")
        self.assertEqual(registry["goal_order"], ["fovea_a7", "a2_p6", "a3_p6"])
        self.assertEqual(registry["selected_timing_cohort"]["period_ns"], 6.5)
        self.assertEqual(contract["genus_default_vectorless"], {
            "primary_input_activity": 0.2,
            "sequential_element_activity": 0.2,
        })
        self.assertEqual(contract["reuse"]["genus_runner"]["path"],
                         "physical/k2_w2_genus/run_genus.py")

    def test_driver_is_exact_native_default_vectorless_driver(self) -> None:
        contract = vectorless.expected_contract()
        base = (ROOT / contract["reuse"]["base_driver"]["path"]).read_bytes()
        actual = vectorless.default_vectorless_driver(ROOT, contract)
        self.assertEqual(actual, base)
        lowered = actual.lower()
        self.assertNotIn(b"read_vcd", lowered)
        self.assertNotIn(b"read_saif", lowered)
        self.assertNotIn(b"set_switching_activity", lowered)
        self.assertEqual(actual.count(b"report_power  >"), 1)

    def test_mutated_default_or_comparability_contract_rejects(self) -> None:
        mutations = []
        period = copy.deepcopy(vectorless.expected_contract())
        period["period_ns"] = 5.7
        mutations.append(period)
        default = copy.deepcopy(vectorless.expected_contract())
        default["genus_default_vectorless"]["primary_input_activity"] = 0.1
        mutations.append(default)
        roster = copy.deepcopy(vectorless.expected_contract())
        roster["candidate_order"] = ["a2_p6", "a3_p6"]
        mutations.append(roster)
        for mutated in mutations:
            with self.subTest(mutated=mutated), self.assertRaises(
                    vectorless.VectorlessError):
                vectorless.validate_contract(ROOT, mutated)

    def test_preflight_is_cadence_free_honest_hold(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "preflight.json"
            result = subprocess.run(
                ["python3", str(FLOW), "preflight", "--repo-root", str(ROOT),
                 "--output", str(output)], text=True, capture_output=True,
                check=False)
            self.assertEqual(result.returncode, 0, result.stderr)
            receipt = json.loads(output.read_text())
            self.assertEqual(receipt["status"], "HOLD_NO_REAL_SERVER_ARTIFACTS")
            self.assertFalse(receipt["comparison_ready"])
            self.assertFalse(receipt["candidate_go"])
            self.assertFalse(receipt["activity_annotated"])
            self.assertEqual(receipt["power_method"], "GENUS_DEFAULT_VECTORLESS")
            self.assertIn("Cadence was not invoked", receipt["reason"])

    def test_preflight_never_calls_native_runner(self) -> None:
        with tempfile.TemporaryDirectory() as temporary, mock.patch.object(
                vectorless.run_genus, "run_flow",
                side_effect=AssertionError("preflight invoked EDA")) as runner:
            vectorless.preflight(ROOT, Path(temporary) / "preflight.json")
            runner.assert_not_called()

    def test_execute_does_not_replace_or_patch_runner_driver(self) -> None:
        source = FLOW.read_text()
        self.assertNotIn("run_genus.DRIVER_TCL =", source)
        self.assertNotIn("TemporaryDirectory", source)
        self.assertIn("run_genus.run_flow(", source)

    def test_execute_rejects_existing_root_before_runner_call(self) -> None:
        with tempfile.TemporaryDirectory() as temporary, mock.patch.object(
                vectorless.run_genus, "run_flow",
                side_effect=AssertionError("runner should not be called")) as runner:
            args = argparse.Namespace(
                attempt_prefix="test", output_root=Path(temporary))
            with self.assertRaises(FileExistsError):
                vectorless.execute(args)
            runner.assert_not_called()

    def test_provider_hashes_are_current(self) -> None:
        contract = vectorless.expected_contract()
        for row in contract["reuse"].values():
            payload = (ROOT / row["path"]).read_bytes()
            self.assertEqual(hashlib.sha256(payload).hexdigest(), row["sha256"])


class PowerReportTest(unittest.TestCase):
    TOP = "w2_a2_p6_physical_staging_top"
    DEFAULTS = {"primary_input_activity": 0.2,
                "sequential_element_activity": 0.2}

    def test_requires_and_parses_exact_native_default_headers(self) -> None:
        result = vectorless.parse_power_report(
            power_report(self.TOP), self.TOP, self.DEFAULTS)
        self.assertAlmostEqual(result["total_mw"], 0.002001)
        self.assertAlmostEqual(result["leakage_mw"], 0.000001)

    def test_missing_activity_headers_mutation_rejects(self) -> None:
        payload = power_report(self.TOP).replace(b"* Activity File: N.A.\n", b"")
        with self.assertRaisesRegex(vectorless.VectorlessError,
                                    "exactly one Activity File"):
            vectorless.parse_power_report(payload, self.TOP, self.DEFAULTS)

    def test_nonexact_or_imported_activity_mutations_reject(self) -> None:
        reports = (
            power_report(self.TOP, activity="N/A"),
            power_report(self.TOP, activity="waves/run.vcd"),
            power_report(self.TOP, user="Imported"),
            power_report(self.TOP, sequential="0.1"),
            power_report(self.TOP, primary="0.3"),
        )
        for report in reports:
            with self.subTest(report=report), self.assertRaises(
                    vectorless.VectorlessError):
                vectorless.parse_power_report(report, self.TOP, self.DEFAULTS)

    def test_wrong_top_units_and_bad_sum_reject(self) -> None:
        valid = power_report(self.TOP)
        mutations = (
            valid.replace(self.TOP.encode(), b"wrong_top"),
            valid.replace(b"Power Unit: W", b"Power Unit: mW"),
            valid.replace(b"2.00100e-06", b"9.00000e-06"),
        )
        for report in mutations:
            with self.subTest(report=report), self.assertRaises(
                    vectorless.VectorlessError):
                vectorless.parse_power_report(report, self.TOP, self.DEFAULTS)


class ProducerEvidenceMutationTest(unittest.TestCase):
    TOP = "w2_a2_p6_physical_staging_top"

    def valid_log(self) -> bytes:
        return (f"Version: 23.14-s090_1\nW2_GENUS_PASS top={self.TOP}\n"
                "Info=12, Warn=3, Error=0, Fatal=0\nNormal exit.\n").encode()

    def test_fake_log_mutations_are_not_proof(self) -> None:
        valid = self.valid_log()
        vectorless.verify_genus_log(valid, self.TOP, "23.14-s090_1")
        mutations = (
            valid.replace(b"Normal exit.\n", b""),
            valid.replace(b"Error=0", b"Error=1"),
            valid.replace(b"W2_GENUS_PASS", b"CALLER_SAYS_PASS"),
            valid + b"set_switching_activity -toggle_rate 0.2 [get_db ports]\n",
        )
        for payload in mutations:
            with self.subTest(payload=payload), self.assertRaises(
                    vectorless.VectorlessError):
                vectorless.verify_genus_log(payload, self.TOP, "23.14-s090_1")

    def test_fake_mapped_netlist_hash_mutation_rejects(self) -> None:
        netlist = b"module mapped(); endmodule\n"
        digest = hashlib.sha256(netlist).hexdigest()
        self.assertEqual(vectorless.verify_bound_bytes(
            netlist, digest, "mapped netlist"), digest)
        with self.assertRaisesRegex(vectorless.VectorlessError, "bytes/hash mismatch"):
            vectorless.verify_bound_bytes(
                netlist + b"// caller mutation\n", digest, "mapped netlist")
        with self.assertRaisesRegex(vectorless.VectorlessError, "malformed"):
            vectorless.verify_bound_bytes(netlist, "caller-says-pass", "mapped netlist")

    def test_actual_server_environment_shape_is_accepted_before_crypto_check(self) -> None:
        contract = vectorless.expected_contract()
        server_contract = json.loads((
            ROOT / contract["reuse"]["server_environment_contract"]["path"]).read_text())
        tool = {"path": "/tool", "resolved_path": "/resolved",
                "entrypoint_kind": "symlink_wrapper", "sha256": "a" * 64,
                "size_bytes": 1, "expected_version": "23.14-s090_1",
                "parsed_version": "23.14-s090_1", "version_output": "Version",
                "warnings": []}
        technology = {name: {"path": "/" + name, "sha256": "b" * 64,
                             "size_bytes": 1}
                      for name in ("setup_liberty", "hold_liberty", "tech_lef",
                                   "macro_lef", "setup_qrc", "hold_qrc")}
        plain_gate = {"status": "PROVEN", "evidence": {}}
        document = {
            "schema": "k2_w2_server_env_result_v1",
            "campaign_launch_allowed": True,
            "qualification_status": "PROVEN_ENVIRONMENT",
            "contract_sha256": contract["reuse"]["server_environment_contract"]["sha256"],
            "direct_server_observation": server_contract["direct_server_observation"],
            "unresolved_environment_evidence": [],
            "corner_policy": server_contract["corner_policy"],
            "environment_binding_sha256": "c" * 64,
            "receipt": {}, "receipt_sha256": "d" * 64,
            "gates": {
                "direct_server_observation": {
                    "status": "PROVEN_DIRECT_OBSERVATION", "evidence": {},
                    "reason": "external observation"},
                "golden_environment": {"status": "PROVEN_PARTIAL", "evidence": {},
                                       "reason": "historical limitation"},
                "source_archives": copy.deepcopy(plain_gate),
                "tool_executables": {"status": "PROVEN", "evidence": {
                    "genus": copy.deepcopy(tool), "innovus": copy.deepcopy(tool),
                    "xrun": copy.deepcopy(tool)}},
                "technology_files": {"status": "PROVEN", "evidence": technology},
                "library_semantics": copy.deepcopy(plain_gate),
                "site_and_cell_availability": copy.deepcopy(plain_gate),
                "rc_policy": copy.deepcopy(plain_gate),
            },
        }
        with mock.patch.object(vectorless.server_preflight, "verify_go_document"):
            self.assertEqual(
                vectorless.validate_environment(vectorless.canonical(document), contract),
                document)
        document["gates"]["technology_files"]["evidence"]["unknown"] = {}
        with mock.patch.object(vectorless.server_preflight, "verify_go_document"):
            with self.assertRaisesRegex(vectorless.VectorlessError, "keys mismatch"):
                vectorless.validate_environment(vectorless.canonical(document), contract)

    def test_unknown_manifest_field_rejects_before_artifact_use(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            path = indexed_manifest(root)
            document = json.loads(path.read_text())
            document["caller_claimed_cadence"] = True
            write_json(path, document)
            with self.assertRaisesRegex(vectorless.VectorlessError, "keys mismatch"):
                vectorless.qualify(path, root / "qualification.json")

    def test_unknown_row_field_rejects_before_attempt_use(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            rows = [{"design": key, "top": registry["designs"][key]["top"],
                     "attempt_directory": "missing-" + key}
                    for key in contract["candidate_order"]]
            rows[0]["caller_status"] = "PASS"
            path = indexed_manifest(root, rows)
            with self.assertRaisesRegex(vectorless.VectorlessError, "keys mismatch"):
                vectorless.qualify(path, root / "qualification.json")

    def test_unknown_attempt_field_rejects(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            attempt_dir = root / "attempt-01"
            attempt = {key: None for key in vectorless.ATTEMPT_KEYS}
            receipt = {key: None for key in vectorless.RECEIPT_KEYS}
            attempt["caller_status"] = "PASS"
            write_json(attempt_dir / "attempt.json", attempt)
            write_json(attempt_dir / "receipt.json", receipt)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            rows = [{"design": key, "top": registry["designs"][key]["top"],
                     "attempt_directory": attempt_dir.name}
                    for key in contract["candidate_order"]]
            path = indexed_manifest(root, rows)
            with self.assertRaisesRegex(vectorless.VectorlessError, "keys mismatch"):
                vectorless.qualify(path, root / "qualification.json")

    def test_non_cadence_receipt_rejects(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            attempt_dir = root / "attempt-01"
            attempt = {key: None for key in vectorless.ATTEMPT_KEYS}
            receipt = {key: None for key in vectorless.RECEIPT_KEYS}
            attempt["schema"] = "caller_authored_attempt"
            receipt["schema"] = "caller_authored_receipt"
            receipt["status"] = "PASS"
            write_json(attempt_dir / "attempt.json", attempt)
            write_json(attempt_dir / "receipt.json", receipt)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            key = contract["candidate_order"][0]
            rows = [{"design": key, "top": registry["designs"][key]["top"],
                     "attempt_directory": attempt_dir.name}]
            # Preserve the exact cohort cardinality without permitting the first
            # fabricated row to be skipped in favor of later rows.
            for later in contract["candidate_order"][1:]:
                rows.append({"design": later, "top": registry["designs"][later]["top"],
                             "attempt_directory": "unused-" + later})
            path = indexed_manifest(root, rows)
            with self.assertRaisesRegex(vectorless.VectorlessError,
                                        "non-Cadence or non-PASS"):
                vectorless.qualify(path, root / "qualification.json")

    def test_old_fabricated_fixture_can_never_be_qualified(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            fabricated = {
                "schema": "k2_endpoint_vectorless_evidence_v1",
                "execution_class": "REAL_SERVER_CADENCE",
                "evidence_class": contract["evidence_class"],
                "candidate_order": contract["candidate_order"],
                "comparability_policy": contract["comparability_policy"],
                "bindings": vectorless.contract_identity(ROOT, contract, registry),
                "rows": [],
            }
            path = root / "fabricated.json"
            write_json(path, fabricated)
            output = root / "qualification.json"
            with self.assertRaises(vectorless.VectorlessError):
                vectorless.qualify(path, output)
            self.assertFalse(output.exists())

    def test_current_v3_cohort_is_forced_hold_never_go(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            rows = []
            verified = []
            for key in contract["candidate_order"]:
                attempt = root / key
                attempt.mkdir()
                rows.append({"design": key, "top": registry["designs"][key]["top"],
                             "attempt_directory": key})
                verified.append({
                    "design": key,
                    "environment_sha256": "a" * 64,
                    "receipt": {
                        "schema": "k2_w2_genus_exact_three_endpoint_receipt_v3"},
                })
            path = indexed_manifest(root, rows)
            output = root / "qualification.json"
            with mock.patch.object(
                    vectorless, "_verify_static_attempt", side_effect=verified):
                vectorless.qualify(path, output)
            result = json.loads(output.read_text())
            self.assertEqual(
                result["status"],
                "HOLD_INHERITED_GENUS_V3_PRODUCER_RECEIPT_INCOMPLETE")
            self.assertFalse(result["candidate_go"])
            self.assertFalse(result["comparison_ready"])
            self.assertFalse(result["activity_annotated"])

    def test_symlinked_attempt_subdirectory_rejects(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            attempt = root / "attempt"
            outside = root / "outside"
            attempt.mkdir()
            outside.mkdir()
            (attempt / "bundle").mkdir()
            (attempt / "logs").mkdir()
            (attempt / "work").symlink_to(outside, target_is_directory=True)
            with self.assertRaisesRegex(vectorless.VectorlessError, "contains symlink"):
                vectorless.reject_symlinks_in_attempt(attempt, "synthetic")


class EvidenceIndexTest(unittest.TestCase):
    def test_index_contains_only_canonical_attempt_locators(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            contract = vectorless.expected_contract()
            registry = vectorless.validate_contract(ROOT, contract)
            attempts = []
            for key in contract["candidate_order"]:
                attempt = root / key
                attempt.mkdir()
                attempts.append((key, attempt))
            evidence = vectorless.build_evidence(root, contract, registry, attempts)
            self.assertNotIn("execution_class", evidence)
            for row in evidence["rows"]:
                self.assertEqual(set(row), {"design", "top", "attempt_directory"})
                self.assertNotIn("sha256", row)


if __name__ == "__main__":
    unittest.main()
