#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path
import sys


if sys.argv[1:] == ["-version"]:
    print("Cadence Genus(TM) Synthesis Solution Version: 23.14-s090_1")
    raise SystemExit(0)

if len(sys.argv) != 4 or sys.argv[1:3] != ["-batch", "-files"]:
    print("unsupported fake Genus invocation", file=sys.stderr)
    raise SystemExit(64)

required = (
    "W2_TOP", "W2_SOURCES_V", "W2_SOURCES_SV", "W2_DEFINES",
    "W2_LIBRARY", "W2_SDC", "W2_OUTPUT",
)
if any(name not in os.environ for name in required):
    print("missing W2 environment", file=sys.stderr)
    raise SystemExit(65)

top = os.environ["W2_TOP"]
output = Path(os.environ["W2_OUTPUT"])
output.mkdir(parents=True, exist_ok=True)
mode = os.environ.get("W2_FAKE_GENUS_MODE", "pass")

cell = "DFFX1"
if mode == "blackbox":
    cell = "UNRESOLVEDX1"
elif mode == "scan":
    cell = "SDFFX1"

prefix = ""
if mode == "defined_blackbox":
    cell = "DEFINED_BLACKBOX"
    prefix = "(* blackbox *) module DEFINED_BLACKBOX(input CK,D, output Q); endmodule\n"
if mode != "report_only":
    (output / f"{top}_netlist.v").write_text(
        prefix + f"module {top}(input wire CK, input wire D, output wire Q);\n"
        f"  {cell} u_state (.CK(CK), .D(D), .Q(Q));\n"
        "endmodule\n"
    )
    (output / f"{top}_out.sdc").write_text("# fake mapped SDC\n")

reports = {
    "area": (
        "============================================================\n"
        "  Generated by:           Genus(TM) Synthesis Solution 23.14-s090_1\n"
        f"  Module:                 {top}\n"
        "============================================================\n"
        "     Instance      Module  Cell-Count  Cell-Area  Net-Area   Total-Area\n"
        f"{top} NA               1      1.000     0.000        1.000\n"
    ),
    "gtiming": (
        "============================================================\n"
        "  Generated by:           Genus(TM) Synthesis Solution 23.14-s090_1\n"
        f"  Module:                 {top}\n"
        "============================================================\n"
        "Path 1: MET (100 ps) Setup Check\n"
        "             Slack:=     100\n"
    ),
    "gpower": (
        f"Instance: /{top}\n"
        "Power Unit: W\n"
        "    Category         Leakage     Internal    Switching        Total\n"
        "    Subtotal     1.00000e-09  1.00000e-06  1.00000e-06  2.00100e-06\n"
    ),
}
for kind, payload in reports.items():
    if mode == "missing_report" and kind == "gtiming":
        continue
    if mode == "bad_report" and kind == "area":
        payload = "fabricated local report\n"
    (output / f"{top}_{kind}.rpt").write_text(payload)

print("Cadence Genus(TM) Synthesis Solution.")
print("Version: 23.14-s090_1, built fixture")
if mode == "bad_summary":
    print("Info=6, Warn=2, Error=1, Fatal=0")
else:
    print("Info=6, Warn=2, Error=0, Fatal=0")
if mode != "missing_pass":
    print(f"W2_GENUS_PASS top={top}")
print("Normal exit.")
raise SystemExit(0)
