#!/usr/bin/env python3
"""Fail-closed qualification gate for one W2 Innovus output directory."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import re
import stat
import sys
from typing import Sequence


COMMAND_SENTINEL = b"W2_INNOVUS_COMMANDS_COMPLETE\n"
CLEAN_SENTINEL = b"W2_INNOVUS_FLOW_CLEAN\n"
INNOVUS_VERSION = "v23.14-s088_1"
HERE = Path(__file__).resolve().parent

TIMING_REPORTS = (
    "setup_timing.rpt",
    "hold_timing.rpt",
    "recovery_timing.rpt",
    "removal_timing.rpt",
    "gating_setup_timing.rpt",
    "gating_hold_timing.rpt",
    "pulse_width_timing.rpt",
    "half_cycle_setup_timing.rpt",
    "half_cycle_hold_timing.rpt",
)
EXPECTED_TIMING_CHECK = {
    "setup_timing.rpt": "setup",
    "hold_timing.rpt": "hold",
    "recovery_timing.rpt": "recovery",
    "removal_timing.rpt": "removal",
    "gating_setup_timing.rpt": "clock gating setup",
    "gating_hold_timing.rpt": "clock gating hold",
    "pulse_width_timing.rpt": "pulse width",
    "half_cycle_setup_timing.rpt": "setup",
    "half_cycle_hold_timing.rpt": "hold",
}
EXPECTED_MACHINE_CHECK = {
    "setup_timing.rpt": "setup",
    "hold_timing.rpt": "hold",
    "recovery_timing.rpt": "recovery",
    "removal_timing.rpt": "removal",
    "gating_setup_timing.rpt": "gating_setup",
    "gating_hold_timing.rpt": "gating_hold",
    "pulse_width_timing.rpt": "pulse_width",
    "half_cycle_setup_timing.rpt": "half_cycle_setup",
    "half_cycle_hold_timing.rpt": "half_cycle_hold",
}
EXPECTED_MACHINE_VIEW = {
    "setup_timing.rpt": "w2_setup_view",
    "hold_timing.rpt": "w2_hold_view",
    "recovery_timing.rpt": "w2_setup_view",
    "removal_timing.rpt": "w2_hold_view",
    "gating_setup_timing.rpt": "w2_setup_view",
    "gating_hold_timing.rpt": "w2_hold_view",
    "pulse_width_timing.rpt": "w2_setup_view",
    "half_cycle_setup_timing.rpt": "w2_setup_view",
    "half_cycle_hold_timing.rpt": "w2_hold_view",
}
ZERO_COUNT_REPORTS = {
    "check_place_post_place.rpt": "placement_violations",
    "check_place_post_route.rpt": "placement_violations",
    "connectivity.rpt": "connectivity_violations",
    "pg_connectivity.rpt": "pg_connectivity_violations",
    "pg_connectivity_post_route.rpt": "pg_connectivity_violations",
    "drc.rpt": "drc_violations",
    "antenna.rpt": "antenna_violations",
    "check_timing.rpt": "unconstrained_paths",
    "check_design_pre_place.rpt": "unresolved_references",
    "check_design_post_route.rpt": "unresolved_references",
}
OTHER_REPORTS = ("area.rpt", "power.rpt", "route.rpt")
HOLD_CLOSURE_REPORT = "hold_closure.machine"
PRE_HOLD_CLOSURE_REPORT = "hold_closure_pre_setup.machine"
SETUP_CLOSURE_REPORT = "setup_closure.machine"
BOUNDARY_TIMING_REPORT = "boundary_timing.machine"
BAD_LOG = re.compile(
    r"^(?:ERROR|FATAL)\s*:|\*\*(?:ERROR|FATAL):|"
    r"SEG(?:MENTATION)?\s+FAULT|INTERRUPT|W2_INNOVUS_FLOW_FATAL",
    re.IGNORECASE | re.MULTILINE,
)
VERSION_LINE = re.compile(r"^Version:\s+(v[^,\s]+)", re.MULTILINE)
MESSAGE_SUMMARY = re.compile(
    r"^\*\*\* Message Summary:\s+[0-9]+ warning\(s\),\s+([0-9]+) error\(s\)\s*$",
    re.MULTILINE,
)
INNOVUS_END = re.compile(
    r'^--- Ending "Innovus" \([^\n]*\) ---\s*\Z', re.MULTILINE
)
NATIVE_REPORT_HEADER = re.compile(
    r"^#\s+Generated by:\s+Cadence Innovus 23\.14-s088_1\s*$", re.MULTILINE
)
SLACK = re.compile(
    r"^\s*(?:=\s*)?slack(?:\s*\([^)]*\)|\s+time)?\s*[:=]?\s*"
    r"([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)\s*$",
    re.IGNORECASE | re.MULTILINE,
)
PATH_CHECK = re.compile(
    r"^Path\s+[0-9]+:\s+(?:MET|VIOLATED)\s+"
    r"((?:User\s+)?(?:Setup|Hold|Recovery|Removal|Clock\s+Gating\s+Setup|"
    r"Clock\s+Gating\s+Hold|Pulse\s*Width)\s+Check|"
    r"(?:Late|Early)\s+External\s+Delay\s+Assertion)\b",
    re.IGNORECASE | re.MULTILINE,
)
COUNT_LINE = re.compile(r"^([a-z][a-z0-9_]*)=([0-9]+)$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")
TIMING_WARNING_ROW = re.compile(
    r"\|\s*(no_drive|no_load)\s*\|[^\n|]*\|\s*([0-9]+)\s*\|",
    re.IGNORECASE,
)
ACTIVITY_ANNOTATION_SUMMARY = re.compile(
    r"^\s*\(Unique nets matched/Total nets\)\s+:\s+"
    r"(0|[1-9][0-9]{0,19})/(0|[1-9][0-9]{0,19})\s+=\s+"
    r"((?:0|[1-9][0-9]?|100)(?:\.[0-9]{1,6})?)%\s*$"
)
NATIVE_COUNT_PATTERNS = {
    "placement_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:place(?:ment)?)[^\n:]*"
        r"violations?\s*[:=]\s*([0-9]+)",
        r"overlapping\s+with\s+other\s+instance\s*:\s*([0-9]+)",
        r"techsite\s+violation\s*:\s*([0-9]+)",
    ),
    "connectivity_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?connectivity\s+violations?\s*[:=]\s*([0-9]+)",
        r"(?:total\s+(?:number\s+of\s+)?)?connectivity\s+errors?\s*[:=]\s*([0-9]+)",
        r"([0-9]+)\s+total\s+info\(s\)\s+created\.",
    ),
    "pg_connectivity_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:special|pg)\s+connectivity\s+violations?\s*[:=]\s*([0-9]+)",
        r"(?:total\s+(?:number\s+of\s+)?)?(?:special|pg)\s+connectivity\s+errors?\s*[:=]\s*([0-9]+)",
        r"([0-9]+)\s+total\s+info\(s\)\s+created\.",
    ),
    "drc_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:drc\s+)?violations?\s*[:=]\s*([0-9]+)",
    ),
    "antenna_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:nets?\s+with\s+)?antenna\s+violations?\s*[:=]\s*([0-9]+)",
    ),
    "unconstrained_paths": (
        r"(?:total\s+(?:number\s+of\s+)?)?unconstrained\s+paths?\s*[:=]\s*([0-9]+)",
    ),
    "unresolved_references": (
        r"(?:total\s+(?:number\s+of\s+)?)?unresolved\s+references?\s*[:=]\s*([0-9]+)",
    ),
}


class QualificationError(ValueError):
    pass


def _regular(path: Path) -> bytes:
    try:
        info = path.lstat()
    except FileNotFoundError as exc:
        raise QualificationError(f"missing artifact: {path}") from exc
    if not stat.S_ISREG(info.st_mode) or path.is_symlink():
        raise QualificationError(f"artifact is not a regular non-symlink file: {path}")
    data = path.read_bytes()
    if not data:
        raise QualificationError(f"artifact is empty: {path}")
    return data


def _text(path: Path) -> str:
    try:
        return _regular(path).decode("utf-8")
    except UnicodeDecodeError as exc:
        raise QualificationError(f"artifact is not UTF-8: {path}") from exc


def _require_clean_log(path: Path) -> str:
    text = _text(path)
    versions = VERSION_LINE.findall(text)
    if versions != [INNOVUS_VERSION]:
        raise QualificationError(
            f"Innovus log version is not exactly {INNOVUS_VERSION}: {path}"
        )
    if BAD_LOG.search(text):
        raise QualificationError(f"Innovus log contains an error/interruption marker: {path}")
    summaries = [int(value) for value in MESSAGE_SUMMARY.findall(text)]
    if not summaries or any(value != 0 for value in summaries):
        raise QualificationError(f"Innovus log lacks an all-zero error summary: {path}")
    if not INNOVUS_END.search(text):
        raise QualificationError(f"Innovus log lacks the normal ending record: {path}")
    return text


def _require_nonempty_directory(path: Path) -> None:
    try:
        info = path.lstat()
    except FileNotFoundError as exc:
        raise QualificationError(f"missing artifact directory: {path}") from exc
    if not stat.S_ISDIR(info.st_mode) or path.is_symlink():
        raise QualificationError(f"artifact directory is invalid: {path}")
    if not any(path.iterdir()):
        raise QualificationError(f"artifact directory is empty: {path}")


def _timing_profile_contract(profile_id: str) -> dict[str, str]:
    registry = json.loads(
        (HERE / "k2_physical_innovus_cohorts.json").read_text(encoding="utf-8"))
    profile = registry.get("timing_profiles", {}).get(profile_id)
    if not isinstance(profile, dict):
        raise QualificationError("execution descriptor timing profile is unknown")
    digest = hashlib.sha256((json.dumps(
        {"id": profile_id, "profile": profile}, indent=2, sort_keys=True
    ) + "\n").encode()).hexdigest()
    hold = profile.get("hold_fix_allow_setup_tns_degrade")
    if hold is not (profile_id in {
            "three_endpoint_5p7ns", "three_endpoint_6p5ns"}):
        raise QualificationError("hold setup-degrade policy does not match profile")
    pointer = registry.get("timing_cohort_manifest", {})
    timing_path = HERE.parents[1] / str(pointer.get("path", ""))
    try:
        timing_payload = timing_path.read_bytes()
        timing_manifest = json.loads(timing_payload)
    except (OSError, json.JSONDecodeError) as error:
        raise QualificationError("Genus timing manifest is unreadable") from error
    manifest_sha = hashlib.sha256(timing_payload).hexdigest()
    genus_profile = timing_manifest.get("cohorts", {}).get(profile_id)
    if (pointer.get("required_schema") != "k2_w2_genus_timing_cohorts_v1" or
            pointer.get("sha256") != manifest_sha or
            timing_manifest.get("schema") != pointer["required_schema"] or
            not isinstance(genus_profile, dict)):
        raise QualificationError("Genus timing manifest/profile mismatch")
    genus_profile_sha = hashlib.sha256((json.dumps(
        {"id": profile_id, "profile": genus_profile}, indent=2, sort_keys=True
    ) + "\n").encode()).hexdigest()
    return {
        "id": profile_id,
        "profile_sha256": digest,
        "genus_timing_manifest_sha256": manifest_sha,
        "genus_timing_profile_sha256": genus_profile_sha,
        "period_ns": profile["period_ns"],
        "hold_fix_allow_setup_tns_degrade": str(hold).lower(),
    }


def _require_technology_contract(
        path: Path, top: str, timing: dict[str, str]) -> dict[str, str]:
    rows: dict[str, str] = {}
    for line in _text(path).splitlines():
        if line.count("=") != 1:
            raise QualificationError("technology contract has a malformed row")
        key, value = line.split("=", 1)
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key) or not value or key in rows:
            raise QualificationError("technology contract has an invalid/duplicate field")
        rows[key] = value
    expected = {
        "schema": "k2_w2_innovus_technology_contract_v2",
        "top": top,
        "setup_library_role": "slow_max_setup",
        "setup_library_basename": "slow_vdd1v0_basicCells.lib",
        "hold_library_role": "fast_min_hold",
        "hold_library_basename": "fast_vdd1v0_basicCells.lib",
        "rc_model": "shared_typical_gpdk045",
        "qrc_source_count": "1",
        "setup_rc_corner": "w2_shared_setup_rc",
        "hold_rc_corner": "w2_shared_hold_rc",
        "qrc_basename": "gpdk045.tch",
        "timing_profile": timing["id"],
        "timing_profile_sha256": timing["profile_sha256"],
        "period_ns": timing["period_ns"],
        "hold_fix_allow_setup_tns_degrade":
            timing["hold_fix_allow_setup_tns_degrade"],
    }
    variable = {
        "cohort", "design", "setup_library_sha256",
        "hold_library_sha256", "qrc_sha256", "innovus_path",
        "innovus_sha256", "tech_lef_sha256", "cell_lef_sha256",
    }
    if set(rows) != set(expected) | variable:
        raise QualificationError("technology contract field set mismatch")
    if any(rows.get(key) != value for key, value in expected.items()):
        raise QualificationError("technology contract role/corner mismatch")
    if rows["cohort"] != "tech_staged_complete_compositions" or not rows["design"]:
        raise QualificationError("technology contract cohort/design mismatch")
    for key in ("setup_library_sha256", "hold_library_sha256", "qrc_sha256"):
        if not SHA256.fullmatch(rows[key]):
            raise QualificationError(f"technology contract {key} is malformed")
    if rows["setup_library_sha256"] == rows["hold_library_sha256"]:
        raise QualificationError("setup and hold Liberty hashes must differ")
    exact = {
        "innovus_path": "/tools/cadence/DDI231/INNOVUS231/bin/innovus",
        "innovus_sha256": "41670b96270692b6139dcae1c8d8721d7b01d41c0725eb22a1ef5ed2d4fbc3aa",
        "tech_lef_sha256": "0310f32fe4fb5009053dcfe36ece6e8d7a1f8e8d6e58a0b6fdd2109c2c919f70",
        "cell_lef_sha256": "7bb39c7adef5704aa10d886f9cc404b06d4f486219ffb4a6a8bbb31f965d52b2",
        "setup_library_sha256": "dec616b7b53aa5166eac9660ba83561a4057ee3b7e62f59f3d4bebad495ffe10",
        "hold_library_sha256": "e63762d156fd929cde2f58b0a5883020d6f16f0a41d3736577d0af6b94191560",
        "qrc_sha256": "a089c567928e3c8653408ebc503cb4e8270732c5f23e6cb23498d51cd6c75bd5",
    }
    if any(rows[key] != value for key, value in exact.items()):
        raise QualificationError("technology contract authoritative SHA mismatch")
    return rows


def _require_execution_descriptor(run_dir: Path, top: str) -> dict[str, str]:
    descriptor_path = run_dir / "status/EXECUTION_DESCRIPTOR.json"
    payload = _regular(descriptor_path)
    recorded = _text(run_dir / "status/EXECUTION_DESCRIPTOR.sha256").strip()
    if not SHA256.fullmatch(recorded) or hashlib.sha256(payload).hexdigest() != recorded:
        raise QualificationError("retained execution descriptor SHA mismatch")
    try:
        document = json.loads(payload)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise QualificationError("retained execution descriptor is invalid JSON") from error
    registry_hash = hashlib.sha256(
        (HERE / "k2_physical_innovus_cohorts.json").read_bytes()).hexdigest()
    authority_hash = hashlib.sha256(
        (HERE / "k2_physical_server_environment.json").read_bytes()).hexdigest()
    binding = document.get("binding", {})
    if document.get("schema") != "k2_w2_innovus_execution_descriptor_v2" or \
            document.get("registry_sha256") != registry_hash or \
            document.get("authority_sha256") != authority_hash or \
            binding.get("top") != top or \
            binding.get("cohort") != "tech_staged_complete_compositions":
        raise QualificationError("retained execution descriptor identity mismatch")
    timing = _timing_profile_contract(binding.get("timing_profile_id", ""))
    if (binding.get("innovus_timing_profile_sha256") !=
            timing["profile_sha256"] or
            binding.get("genus_timing_manifest_sha256") !=
            timing["genus_timing_manifest_sha256"] or
            binding.get("genus_timing_profile_sha256") !=
            timing["genus_timing_profile_sha256"] or
            binding.get("period_ns") != timing["period_ns"] or
            str(binding.get("hold_fix_allow_setup_tns_degrade")).lower() !=
            timing["hold_fix_allow_setup_tns_degrade"]):
        raise QualificationError("retained execution descriptor timing mismatch")
    return timing


def _require_activity_contract(path: Path) -> dict[str, str]:
    rows = {}
    for line in _text(path).splitlines():
        if line.count("=") != 1:
            raise QualificationError("activity contract malformed")
        key, value = line.split("=", 1)
        if key in rows or not value:
            raise QualificationError("activity contract duplicate/empty field")
        rows[key] = value
    if set(rows) != {"schema", "mode", "format", "scope", "activity_sha256",
                     "window_start_ns", "window_end_ns"} or \
            rows["schema"] != "k2_w2_activity_power_contract_v1" or \
            rows["mode"] != "annotated_activity" or rows["format"] not in {"SAIF", "VCD"} or \
            not SHA256.fullmatch(rows["activity_sha256"]):
        raise QualificationError("vectorless or invalid activity power contract")
    try:
        start, end = float(rows["window_start_ns"]), float(rows["window_end_ns"])
    except ValueError as error:
        raise QualificationError("activity window is not numeric") from error
    if start < 0 or end <= start:
        raise QualificationError("activity window is empty/reversed")
    return rows


def _require_boundary_timing(path: Path, timing: dict[str, str]) -> None:
    rows: dict[str, str] = {}
    for line in _text(path).splitlines():
        if line.count("=") != 1:
            raise QualificationError("boundary timing report malformed")
        key, value = line.split("=", 1)
        if key in rows or not value:
            raise QualificationError("boundary timing report duplicate/empty field")
        rows[key] = value
    expected = {
        "schema": "k2_w2_boundary_timing_v1",
        "timing_profile": timing["id"],
        "timing_profile_sha256": timing["profile_sha256"],
        "period_ns": timing["period_ns"],
        "clock_ports": "ref_clk_i,sample_clk_i",
        "clock_drive": "0",
        "nonclock_input_ports": "rst_n,source_pending_i",
        "nonclock_driving_cell": "BUFX2",
        "forwarded_link_clock": "*w2_ep_icg_0/ECK,link_clk_o,divide_by_1",
        "link_clock_false_path": "FORBIDDEN",
        "hold_fix_allow_setup_tns_degrade":
            timing["hold_fix_allow_setup_tns_degrade"],
    }
    if rows != expected:
        raise QualificationError("boundary timing/profile contract mismatch")


def _activity_annotation(path: Path) -> dict[str, float | int]:
    text = _text(path)
    header = "Annotation coverage for this file"
    label = "(Unique nets matched/Total nets)"
    completion = "'read_activity_file' finished successfully."
    lines = text.splitlines()
    header_indexes = [index for index, line in enumerate(lines) if header in line]
    summary_indexes = [index for index, line in enumerate(lines) if label in line]
    completion_indexes = [
        index for index, line in enumerate(lines) if completion in line
    ]
    if len(header_indexes) != 1 or len(summary_indexes) != 1 or \
            len(completion_indexes) != 1:
        raise QualificationError(
            f"activity annotation report must contain exactly one native summary: {path}"
        )
    if lines[header_indexes[0]].strip() != header or \
            summary_indexes[0] != header_indexes[0] + 1 or \
            lines[completion_indexes[0]].strip() != completion or \
            completion_indexes[0] <= summary_indexes[0]:
        raise QualificationError(f"activity annotation summary is malformed: {path}")
    if BAD_LOG.search(text):
        raise QualificationError(f"activity annotation report contains an error: {path}")
    match = ACTIVITY_ANNOTATION_SUMMARY.fullmatch(lines[summary_indexes[0]])
    if match is None:
        raise QualificationError(f"activity annotation summary is malformed: {path}")
    matched_token, total_token, percentage_token = match.groups()
    matched, total = int(matched_token), int(total_token)
    percentage_parts = percentage_token.split(".", 1)
    decimal_places = len(percentage_parts[1]) if len(percentage_parts) == 2 else 0
    percentage_scale = 10 ** decimal_places
    percentage_scaled = int("".join(percentage_parts))
    percentage = percentage_scaled / percentage_scale
    if matched <= 0 or total <= 0 or matched > total or \
            percentage_scaled <= 0 or percentage_scaled > 100 * percentage_scale:
        raise QualificationError(f"activity annotation coverage is zero/invalid: {path}")
    # Innovus rounds the fraction at the displayed decimal precision.  Check
    # that relationship with integer arithmetic so hostile huge counts cannot
    # overflow a float or turn into an unhandled non-finite value.
    scaled_difference = abs(
        percentage_scaled * total - 100 * matched * percentage_scale
    )
    if 2 * scaled_difference > total:
        raise QualificationError(
            f"activity annotation count/percentage mismatch: {path}"
        )
    return {
        "matched_nets": matched,
        "total_nets": total,
        "coverage_percent": percentage,
    }


def _timing_machine_summary(
    path: Path, expected: str, expected_view: str
) -> dict[str, float | int | str]:
    rows = {}
    for line in _text(path).splitlines():
        if line.count("=") != 1:
            raise QualificationError(f"timing machine summary malformed: {path}")
        key, value = line.split("=", 1)
        if key in rows:
            raise QualificationError(f"timing machine summary duplicate field: {path}")
        rows[key] = value
    if set(rows) != {"schema", "check", "view", "path_count", "violation_count", "wns", "tns"} or \
            rows["schema"] != "k2_w2_timing_machine_summary_v1" or \
            rows["check"] != expected or rows["view"] != expected_view:
        raise QualificationError(f"timing machine summary contract mismatch: {path}")
    try:
        path_count = int(rows["path_count"])
        violations = int(rows["violation_count"])
        wns, tns = float(rows["wns"]), float(rows["tns"])
    except ValueError as error:
        raise QualificationError(f"timing machine summary numeric mismatch: {path}") from error
    if path_count <= 0 or violations != 0 or wns < 0.0 or tns != 0.0 or \
            not math.isfinite(wns) or not math.isfinite(tns):
        raise QualificationError(f"timing machine summary is not clean: {path}")
    return {"check": expected, "path_count": path_count, "violation_count": violations,
            "wns": wns, "tns": tns}


def _require_timing_closure(
    path: Path, expected_schema: str, expected_meta: dict[str, str], maximum_expected: int
) -> tuple[int, int, float, float]:
    rows = {}
    for line in _text(path).splitlines():
        if line.count("=") != 1:
            raise QualificationError(f"hold closure report malformed: {path}")
        key, value = line.split("=", 1)
        if key in rows or not value:
            raise QualificationError(f"hold closure report duplicate/empty field: {path}")
        rows[key] = value
    try:
        maximum = int(rows.pop("max_iterations"))
        count = int(rows.pop("observation_count"))
    except (KeyError, ValueError) as error:
        raise QualificationError(f"hold closure report count mismatch: {path}") from error
    if rows.pop("schema", None) != expected_schema or \
            rows.pop("status", None) != "CLOSED" or maximum != maximum_expected or \
            count < 1 or count > maximum + 1:
        raise QualificationError(f"hold closure report contract mismatch: {path}")
    for key, value in expected_meta.items():
        if rows.pop(key, None) != value:
            raise QualificationError(f"timing closure metadata mismatch: {path}")
    if set(rows) != {f"observation_{index}" for index in range(count)}:
        raise QualificationError(f"timing closure unexpected fields: {path}")
    previous = None
    for index in range(count):
        tokens = rows[f"observation_{index}"].split(",")
        try:
            paths, violations = map(int, tokens[:2])
            wns, tns = map(float, tokens[2:])
        except (ValueError, TypeError) as error:
            raise QualificationError(f"hold closure observation malformed: {path}") from error
        current = (paths, violations, wns, tns)
        if len(tokens) != 4 or paths <= 0 or violations < 0 or \
                not math.isfinite(wns) or not math.isfinite(tns):
            raise QualificationError(f"hold closure observation invalid: {path}")
        is_final = index == count - 1
        if (is_final and (violations != 0 or wns < 0.0 or tns != 0.0)) or \
                (not is_final and (violations <= 0 or wns >= 0.0 or tns >= 0.0)):
            raise QualificationError(f"timing closure observation phase mismatch: {path}")
        if previous is not None and not (
                violations < previous[1] or
                (violations == previous[1] and
                 (wns > previous[2] + 0.000001 or
                  (abs(wns - previous[2]) <= 0.000001 and
                   tns > previous[3] + 0.000001)))):
            raise QualificationError(f"hold closure did not improve monotonically: {path}")
        previous = current
    if previous is None or previous[1] != 0 or previous[2] < 0.0 or previous[3] != 0.0:
        raise QualificationError(f"hold closure final observation is not clean: {path}")
    return previous


def _require_hold_closure(path: Path, phase: str, policy: str) -> tuple[int, int, float, float]:
    return _require_timing_closure(path, "k2_w2_hold_closure_v1", {
        "phase": phase, "check": "hold", "view": "w2_hold_view",
        "optimizer": "postRoute_hold", "allow_setup_tns_degrade": policy,
    }, 3)


def _require_setup_closure(path: Path) -> tuple[int, int, float, float]:
    return _require_timing_closure(path, "k2_w2_setup_closure_v1", {
        "phase": "setup_recovery", "check": "setup", "view": "w2_setup_view",
        "optimizer": "postRoute", "allow_setup_tns_degrade": "NA",
    }, 6)


def _require_check_design_all(path: Path) -> None:
    text = _text(path)
    counts = _canonical_counts(path)
    if "check_design_errors" in counts or "check_design_violations" in counts:
        if counts.get("check_design_errors") != 0 or \
                counts.get("check_design_violations") != 0:
            raise QualificationError(
                f"checkDesign all-class summary is absent/nonzero: {path}")
    else:
        summaries = MESSAGE_SUMMARY.findall(text)
        if text.count("Design check done.") != 1 or len(summaries) != 1 or \
                int(summaries[0]) != 0:
            raise QualificationError(
                f"native checkDesign completion/error summary mismatch: {path}")
        if re.search(r"(?mi)^.*unresolved\s+references?.*:\s*[1-9][0-9]*\s*$", text):
            raise QualificationError(f"native checkDesign unresolved references: {path}")
    if re.search(r"(?mi)^\s*(?:\*\*)?(?:ERROR|FATAL|VIOLATION)\b", text):
        raise QualificationError(f"checkDesign native report contains an error class: {path}")


def _require_route_complete(path: Path) -> None:
    text = _text(path)
    counts = _canonical_counts(path)
    if "detailed_route_completed" in counts:
        if counts.get("detailed_route_completed") != 1:
            raise QualificationError("detailed route is not canonically complete")
        return

    # Innovus 23.14 reportRoute does not print a prose "detailed route
    # completed" marker.  Its native successful-command footer and routed
    # geometry totals are the stable, fail-closed completion evidence.  DRC,
    # connectivity and placement are independently gated elsewhere.
    if len(re.findall(r"(?m)^#Number of fails = 0\s*$", text)) != 1 or \
            len(re.findall(r"(?m)^#Total number of fails = 0\s*$", text)) != 1 or \
            len(re.findall(r"(?m)^#Complete\s+on\s+.+$", text)) != 1:
        raise QualificationError("native route completion/failure summary mismatch")
    net_length = re.findall(
        r"(?m)^Total net length\s*=\s*"
        r"([0-9]+(?:\.[0-9]*)?(?:[eE][-+]?[0-9]+)?)\s*\(", text)
    geometry = re.findall(
        r"(?m)^Total length:\s*"
        r"([0-9]+(?:\.[0-9]*)?(?:[eE][-+]?[0-9]+)?)um,\s*"
        r"number of vias:\s*([0-9]+)\s*$", text)
    if len(net_length) != 1 or len(geometry) != 1 or \
            float(net_length[0]) <= 0.0 or float(geometry[0][0]) <= 0.0 or \
            int(geometry[0][1]) <= 0:
        raise QualificationError("native route geometry summary mismatch")


def _timing_observation(path: Path, expected_check: str | None = None) -> tuple[str, float]:
    text = _text(path)
    checks = {re.sub(r"\s+", " ", value.lower()) for value in PATH_CHECK.findall(text)}
    checks = {
        re.sub(r"^(?:user )?| check$", "", value).strip()
        for value in checks
    }
    checks = {"pulse width" if value == "pulsewidth" else value for value in checks}
    checks = {
        "setup" if value == "late external delay assertion" else
        "hold" if value == "early external delay assertion" else value
        for value in checks
    }
    if len(checks) != 1:
        raise QualificationError(
            f"timing report must contain exactly one check class: {path}"
        )
    check = next(iter(checks))
    if expected_check is not None and check != expected_check:
        raise QualificationError(
            f"timing report check class is {check}, expected {expected_check}: {path}"
        )
    values = []
    for token in SLACK.findall(text):
        value = float(token)
        if not math.isfinite(value):
            raise QualificationError(f"non-finite timing slack: {path}")
        values.append(value)
    if not values:
        raise QualificationError(f"timing report has no recognized slack path: {path}")
    return check, min(values)


def _timing_slack(path: Path) -> float:
    return _timing_observation(path)[1]


def _canonical_counts(path: Path) -> dict[str, int]:
    result: dict[str, int] = {}
    for line in _text(path).splitlines():
        match = COUNT_LINE.fullmatch(line)
        if match:
            key, token = match.groups()
            if key in result:
                raise QualificationError(f"duplicate canonical count {key}: {path}")
            result[key] = int(token)
    return result


def _require_zero(path: Path, key: str) -> None:
    text = _text(path)
    counts = _canonical_counts(path)
    values = [counts[key]] if key in counts else []
    for pattern in NATIVE_COUNT_PATTERNS[key]:
        values.extend(
            int(token) for token in re.findall(pattern, text, re.IGNORECASE)
        )
    has_native_header = bool(NATIVE_REPORT_HEADER.search(text))
    if key == "placement_violations" and \
            text.startswith("Begin checking placement") and \
            "Finished checkPlace" in text and not values:
        values.append(0)
    if key in {"connectivity_violations", "pg_connectivity_violations"} and \
            has_native_header and re.search(
                r"^\s*Found no problems or warnings\.\s*$", text,
                re.IGNORECASE | re.MULTILINE):
        values.append(0)
    if key == "drc_violations" and has_native_header and re.search(
        r"^No DRC violations were found\s*$", text, re.IGNORECASE | re.MULTILINE
    ):
        values.append(0)
    if key == "antenna_violations" and has_native_header and re.search(
        r"^No Violations Found\s*$", text, re.IGNORECASE | re.MULTILINE
    ):
        values.append(0)
    if (
        key == "unconstrained_paths"
        and has_native_header
        and "TIMING CHECK SUMMARY" in text
        and "Warning Description" in text
        and "TIMING CHECK DETAIL" in text
    ):
        # Innovus 23.14 prints only warning classes with nonzero counts.  The
        # golden has ideal_clock_waveform/no_drive but no missing-clock or
        # missing-I/O-delay class, so those warnings are not conflated with
        # unconstrained endpoints.
        blockers = re.findall(
            r"\|\s*(no_clock|no_input_delay|no_output_delay|unconstrained)\s*\|",
            text, re.IGNORECASE,
        )
        if not blockers:
            values.append(0)
    if not values:
        raise QualificationError(f"report lacks recognized {key} count: {path}")
    if any(value != 0 for value in values):
        raise QualificationError(f"{key} is nonzero ({max(values)}): {path}")


def validate_minimum_signoff(
    log_path: Path,
    setup_path: Path,
    hold_path: Path,
    drc_path: Path,
    antenna_path: Path,
    check_timing_path: Path,
) -> dict[str, float]:
    """Qualify the minimum server signoff set by content, never existence."""
    _require_clean_log(log_path)
    warning_counts = {"no_drive": 0, "no_load": 0}
    for name, value in TIMING_WARNING_ROW.findall(_text(check_timing_path)):
        warning_counts[name.lower()] += int(value)
    if warning_counts["no_drive"] or warning_counts["no_load"]:
        raise QualificationError(
            f"check_timing has no_drive/no_load warnings: {warning_counts}")
    slacks = {
        "setup": _timing_observation(setup_path, "setup")[1],
        "hold": _timing_observation(hold_path, "hold")[1],
    }
    for check, value in slacks.items():
        if value < 0.0:
            raise QualificationError(f"{check} WNS is negative ({value})")
    _require_zero(drc_path, "drc_violations")
    _require_zero(antenna_path, "antenna_violations")
    _require_zero(check_timing_path, "unconstrained_paths")
    return slacks


def validate(run_dir: Path, top: str) -> dict[str, float]:
    if not top or "/" in top or top in {".", ".."}:
        raise QualificationError("top must be one simple module name")
    marker = run_dir / "status" / "COMMANDS_COMPLETE"
    if _regular(marker) != COMMAND_SENTINEL:
        raise QualificationError("Innovus command-completion sentinel mismatch")
    if (run_dir / "status" / "COMMANDS_FAILED").exists():
        raise QualificationError("Innovus failure sentinel is present")
    if (run_dir / "status" / "FLOW_CLEAN").exists():
        raise QualificationError("FLOW_CLEAN already exists")
    timing = _require_execution_descriptor(run_dir, top)
    _require_technology_contract(
        run_dir / "status" / "TECHNOLOGY_CONTRACT", top, timing
    )
    _require_activity_contract(run_dir / "status" / "ACTIVITY_POWER_CONTRACT")
    _require_hold_closure(
        run_dir / "reports" / PRE_HOLD_CLOSURE_REPORT,
        "pre_setup_hold", str(timing["hold_fix_allow_setup_tns_degrade"]).lower())
    _require_setup_closure(run_dir / "reports" / SETUP_CLOSURE_REPORT)
    final_hold_closure = _require_hold_closure(
        run_dir / "reports" / HOLD_CLOSURE_REPORT, "final_hold_reclosure",
        str(timing["hold_fix_allow_setup_tns_degrade"]).lower())
    _require_boundary_timing(
        run_dir / "reports" / BOUNDARY_TIMING_REPORT, timing)

    reports = run_dir / "reports"
    _activity_annotation(reports / "activity_annotation.rpt")
    slacks = validate_minimum_signoff(
        run_dir / "tool.log",
        reports / "setup_timing.rpt",
        reports / "hold_timing.rpt",
        reports / "drc.rpt",
        reports / "antenna.rpt",
        reports / "check_timing.rpt",
    )
    for name in TIMING_REPORTS[2:]:
        _, slack = _timing_observation(
            reports / name, EXPECTED_TIMING_CHECK[name]
        )
        slacks[name[:-len("_timing.rpt")]] = slack
    for check, value in slacks.items():
        if value < 0.0:
            raise QualificationError(f"{check} WNS is negative ({value})")
    machine_summaries = {}
    for name in TIMING_REPORTS:
        check = EXPECTED_MACHINE_CHECK[name]
        summary = _timing_machine_summary(
            reports / name.replace(".rpt", ".machine"), check,
            EXPECTED_MACHINE_VIEW[name],
        )
        machine_summaries[name] = summary
        slack_key = name[:-len("_timing.rpt")]
        # Native 23.14 text reports print slack to 0.001 ns while the machine
        # collection retains full precision.  Require agreement within exactly
        # one half of the native least-significant digit.
        if abs(float(summary["wns"]) - slacks[slack_key]) > 0.0005001:
            raise QualificationError(f"native timing report/machine WNS mismatch: {name}")
    final_hold_summary = machine_summaries["hold_timing.rpt"]
    if final_hold_closure[:2] != (
            int(final_hold_summary["path_count"]),
            int(final_hold_summary["violation_count"])) or \
            abs(final_hold_closure[2] - float(final_hold_summary["wns"])) > 1e-9 or \
            abs(final_hold_closure[3] - float(final_hold_summary["tns"])) > 1e-9:
        raise QualificationError("final hold closure and timing summary mismatch")
    # Post-place overlap counts are an intermediate diagnostic: CTS/route ECO
    # legalizes them.  The post-route placement report is the signoff gate.
    # Retain and require the intermediate report, but do not rank/fail on it.
    _regular(reports / "check_place_post_place.rpt")
    minimum_zero_reports = {
        "drc.rpt", "antenna.rpt", "check_timing.rpt",
        "check_place_post_place.rpt",
        "check_design_pre_place.rpt", "check_design_post_route.rpt",
    }
    for name, key in ZERO_COUNT_REPORTS.items():
        if name in minimum_zero_reports:
            continue
        _require_zero(reports / name, key)
    for name in OTHER_REPORTS:
        _regular(reports / name)
    _require_check_design_all(reports / "check_design_pre_place.rpt")
    _require_check_design_all(reports / "check_design_post_route.rpt")
    _require_route_complete(reports / "route.rpt")

    _regular(run_dir / "netlist" / f"{top}.postroute.v")
    sdf = _regular(run_dir / "netlist" / f"{top}.postroute.sdf")
    spef = _regular(run_dir / "netlist" / f"{top}.postroute.spef")
    if b"(DELAYFILE" not in sdf or top.encode() not in sdf:
        raise QualificationError("post-route SDF is malformed or bound to another top")
    if b"*SPEF" not in spef or top.encode() not in spef:
        raise QualificationError("post-route SPEF is malformed or bound to another top")
    _require_nonempty_directory(run_dir / "database")
    return slacks


def _write_exclusive(path: Path, payload: bytes) -> None:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(path, flags, 0o644)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
    finally:
        os.close(descriptor)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--top", required=True)
    parser.add_argument("--write-clean-marker", action="store_true")
    args = parser.parse_args(argv)
    try:
        slacks = validate(args.run_dir.resolve(), args.top)
        if args.write_clean_marker:
            _write_exclusive(args.run_dir / "status" / "FLOW_CLEAN", CLEAN_SENTINEL)
    except (OSError, QualificationError) as exc:
        print(f"W2_INNOVUS_NOT_CLEAN: {exc}", file=sys.stderr)
        return 2
    values = " ".join(f"{name}_wns={value:g}" for name, value in sorted(slacks.items()))
    print(f"W2_INNOVUS_FLOW_CLEAN {values}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
