#!/usr/bin/env python3
"""Fail-closed qualification gate for one W2 Innovus output directory."""

from __future__ import annotations

import argparse
import math
import os
from pathlib import Path
import re
import stat
import sys
from typing import Sequence


COMMAND_SENTINEL = b"W2_INNOVUS_COMMANDS_COMPLETE\n"
CLEAN_SENTINEL = b"W2_INNOVUS_FLOW_CLEAN\n"
INNOVUS_VERSION = "v23.14-s088_1"

TIMING_REPORTS = (
    "setup_timing.rpt",
    "hold_timing.rpt",
    "recovery_timing.rpt",
    "removal_timing.rpt",
)
EXPECTED_TIMING_CHECK = {
    "setup_timing.rpt": "setup",
    "hold_timing.rpt": "hold",
    "recovery_timing.rpt": "recovery",
    "removal_timing.rpt": "removal",
}
ZERO_COUNT_REPORTS = {
    "check_place_post_place.rpt": "placement_violations",
    "check_place_post_route.rpt": "placement_violations",
    "connectivity.rpt": "connectivity_violations",
    "pg_connectivity.rpt": "pg_connectivity_violations",
    "pg_connectivity_post_route.rpt": "pg_connectivity_violations",
    "drc.rpt": "drc_violations",
    "antenna.rpt": "antenna_violations",
    "check_timing.rpt": "unconstrained_paths",
    "check_design_pre_place.rpt": "unresolved_references",
    "check_design_post_route.rpt": "unresolved_references",
}
OTHER_REPORTS = ("area.rpt", "power.rpt", "route.rpt")
BAD_LOG = re.compile(
    r"(?:^|\s)(?:ERROR|FATAL)(?::|\s)|\*\*(?:ERROR|FATAL):|"
    r"SEG(?:MENTATION)?\s+FAULT|INTERRUPT|W2_INNOVUS_FLOW_FATAL",
    re.IGNORECASE | re.MULTILINE,
)
VERSION_LINE = re.compile(r"^Version:\s+(v[^,\s]+)", re.MULTILINE)
MESSAGE_SUMMARY = re.compile(
    r"^\*\*\* Message Summary:\s+[0-9]+ warning\(s\),\s+([0-9]+) error\(s\)\s*$",
    re.MULTILINE,
)
INNOVUS_END = re.compile(
    r'^--- Ending "Innovus" \([^\n]*\) ---\s*\Z', re.MULTILINE
)
NATIVE_REPORT_HEADER = re.compile(
    r"^#\s+Generated by:\s+Cadence Innovus 23\.14-s088_1\s*$", re.MULTILINE
)
SLACK = re.compile(
    r"^\s*(?:=\s*)?slack(?:\s*\([^)]*\)|\s+time)?\s*[:=]?\s*"
    r"([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)\s*$",
    re.IGNORECASE | re.MULTILINE,
)
PATH_CHECK = re.compile(
    r"^Path\s+[0-9]+:\s+(?:MET|VIOLATED)\s+"
    r"(Setup|Hold|Recovery|Removal)\s+Check\b",
    re.IGNORECASE | re.MULTILINE,
)
COUNT_LINE = re.compile(r"^([a-z][a-z0-9_]*)=([0-9]+)$")
NATIVE_COUNT_PATTERNS = {
    "placement_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:place(?:ment)?)[^\n:]*"
        r"violations?\s*[:=]\s*([0-9]+)",
    ),
    "connectivity_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?connectivity\s+violations?\s*[:=]\s*([0-9]+)",
        r"(?:total\s+(?:number\s+of\s+)?)?connectivity\s+errors?\s*[:=]\s*([0-9]+)",
    ),
    "pg_connectivity_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:special|pg)\s+connectivity\s+violations?\s*[:=]\s*([0-9]+)",
        r"(?:total\s+(?:number\s+of\s+)?)?(?:special|pg)\s+connectivity\s+errors?\s*[:=]\s*([0-9]+)",
    ),
    "drc_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:drc\s+)?violations?\s*[:=]\s*([0-9]+)",
    ),
    "antenna_violations": (
        r"(?:total\s+(?:number\s+of\s+)?)?(?:nets?\s+with\s+)?antenna\s+violations?\s*[:=]\s*([0-9]+)",
    ),
    "unconstrained_paths": (
        r"(?:total\s+(?:number\s+of\s+)?)?unconstrained\s+paths?\s*[:=]\s*([0-9]+)",
    ),
    "unresolved_references": (
        r"(?:total\s+(?:number\s+of\s+)?)?unresolved\s+references?\s*[:=]\s*([0-9]+)",
    ),
}


class QualificationError(ValueError):
    pass


def _regular(path: Path) -> bytes:
    try:
        info = path.lstat()
    except FileNotFoundError as exc:
        raise QualificationError(f"missing artifact: {path}") from exc
    if not stat.S_ISREG(info.st_mode) or path.is_symlink():
        raise QualificationError(f"artifact is not a regular non-symlink file: {path}")
    data = path.read_bytes()
    if not data:
        raise QualificationError(f"artifact is empty: {path}")
    return data


def _text(path: Path) -> str:
    try:
        return _regular(path).decode("utf-8")
    except UnicodeDecodeError as exc:
        raise QualificationError(f"artifact is not UTF-8: {path}") from exc


def _require_clean_log(path: Path) -> str:
    text = _text(path)
    versions = VERSION_LINE.findall(text)
    if versions != [INNOVUS_VERSION]:
        raise QualificationError(
            f"Innovus log version is not exactly {INNOVUS_VERSION}: {path}"
        )
    if BAD_LOG.search(text):
        raise QualificationError(f"Innovus log contains an error/interruption marker: {path}")
    summaries = [int(value) for value in MESSAGE_SUMMARY.findall(text)]
    if not summaries or any(value != 0 for value in summaries):
        raise QualificationError(f"Innovus log lacks an all-zero error summary: {path}")
    if not INNOVUS_END.search(text):
        raise QualificationError(f"Innovus log lacks the normal ending record: {path}")
    return text


def _require_nonempty_directory(path: Path) -> None:
    try:
        info = path.lstat()
    except FileNotFoundError as exc:
        raise QualificationError(f"missing artifact directory: {path}") from exc
    if not stat.S_ISDIR(info.st_mode) or path.is_symlink():
        raise QualificationError(f"artifact directory is invalid: {path}")
    if not any(path.iterdir()):
        raise QualificationError(f"artifact directory is empty: {path}")


def _timing_observation(path: Path, expected_check: str | None = None) -> tuple[str, float]:
    text = _text(path)
    checks = {value.lower() for value in PATH_CHECK.findall(text)}
    if len(checks) != 1:
        raise QualificationError(
            f"timing report must contain exactly one check class: {path}"
        )
    check = next(iter(checks))
    if expected_check is not None and check != expected_check:
        raise QualificationError(
            f"timing report check class is {check}, expected {expected_check}: {path}"
        )
    values = []
    for token in SLACK.findall(text):
        value = float(token)
        if not math.isfinite(value):
            raise QualificationError(f"non-finite timing slack: {path}")
        values.append(value)
    if not values:
        raise QualificationError(f"timing report has no recognized slack path: {path}")
    return check, min(values)


def _timing_slack(path: Path) -> float:
    return _timing_observation(path)[1]


def _canonical_counts(path: Path) -> dict[str, int]:
    result: dict[str, int] = {}
    for line in _text(path).splitlines():
        match = COUNT_LINE.fullmatch(line)
        if match:
            key, token = match.groups()
            if key in result:
                raise QualificationError(f"duplicate canonical count {key}: {path}")
            result[key] = int(token)
    return result


def _require_zero(path: Path, key: str) -> None:
    text = _text(path)
    counts = _canonical_counts(path)
    values = [counts[key]] if key in counts else []
    for pattern in NATIVE_COUNT_PATTERNS[key]:
        values.extend(
            int(token) for token in re.findall(pattern, text, re.IGNORECASE)
        )
    has_native_header = bool(NATIVE_REPORT_HEADER.search(text))
    if key == "drc_violations" and has_native_header and re.search(
        r"^No DRC violations were found\s*$", text, re.IGNORECASE | re.MULTILINE
    ):
        values.append(0)
    if key == "antenna_violations" and has_native_header and re.search(
        r"^No Violations Found\s*$", text, re.IGNORECASE | re.MULTILINE
    ):
        values.append(0)
    if (
        key == "unconstrained_paths"
        and has_native_header
        and "TIMING CHECK SUMMARY" in text
        and "Warning Description" in text
        and "TIMING CHECK DETAIL" in text
    ):
        # Innovus 23.14 prints only warning classes with nonzero counts.  The
        # golden has ideal_clock_waveform/no_drive but no missing-clock or
        # missing-I/O-delay class, so those warnings are not conflated with
        # unconstrained endpoints.
        blockers = re.findall(
            r"\|\s*(no_clock|no_input_delay|no_output_delay|unconstrained)\s*\|",
            text, re.IGNORECASE,
        )
        if not blockers:
            values.append(0)
    if not values:
        raise QualificationError(f"report lacks recognized {key} count: {path}")
    if any(value != 0 for value in values):
        raise QualificationError(f"{key} is nonzero ({max(values)}): {path}")


def validate_minimum_signoff(
    log_path: Path,
    setup_path: Path,
    hold_path: Path,
    drc_path: Path,
    antenna_path: Path,
    check_timing_path: Path,
) -> dict[str, float]:
    """Qualify the minimum server signoff set by content, never existence."""
    _require_clean_log(log_path)
    slacks = {
        "setup": _timing_observation(setup_path, "setup")[1],
        "hold": _timing_observation(hold_path, "hold")[1],
    }
    for check, value in slacks.items():
        if value < 0.0:
            raise QualificationError(f"{check} WNS is negative ({value})")
    _require_zero(drc_path, "drc_violations")
    _require_zero(antenna_path, "antenna_violations")
    _require_zero(check_timing_path, "unconstrained_paths")
    return slacks


def validate(run_dir: Path, top: str) -> dict[str, float]:
    if not top or "/" in top or top in {".", ".."}:
        raise QualificationError("top must be one simple module name")
    marker = run_dir / "status" / "COMMANDS_COMPLETE"
    if _regular(marker) != COMMAND_SENTINEL:
        raise QualificationError("Innovus command-completion sentinel mismatch")
    if (run_dir / "status" / "COMMANDS_FAILED").exists():
        raise QualificationError("Innovus failure sentinel is present")
    if (run_dir / "status" / "FLOW_CLEAN").exists():
        raise QualificationError("FLOW_CLEAN already exists")

    reports = run_dir / "reports"
    slacks = validate_minimum_signoff(
        run_dir / "tool.log",
        reports / "setup_timing.rpt",
        reports / "hold_timing.rpt",
        reports / "drc.rpt",
        reports / "antenna.rpt",
        reports / "check_timing.rpt",
    )
    for name in TIMING_REPORTS[2:]:
        _, slack = _timing_observation(
            reports / name, EXPECTED_TIMING_CHECK[name]
        )
        slacks[name.removesuffix("_timing.rpt")] = slack
    for check, value in slacks.items():
        if value < 0.0:
            raise QualificationError(f"{check} WNS is negative ({value})")
    minimum_zero_reports = {"drc.rpt", "antenna.rpt", "check_timing.rpt"}
    for name, key in ZERO_COUNT_REPORTS.items():
        if name in minimum_zero_reports:
            continue
        _require_zero(reports / name, key)
    for name in OTHER_REPORTS:
        _regular(reports / name)
    route_text = _text(reports / "route.rpt")
    route = _canonical_counts(reports / "route.rpt")
    native_route_complete = re.search(
        r"detailed\s+route(?:ing)?\s+(?:is\s+)?completed", route_text,
        re.IGNORECASE,
    )
    if route.get("detailed_route_completed") != 1 and not native_route_complete:
        raise QualificationError("detailed route is not canonically complete")

    _regular(run_dir / "netlist" / f"{top}.postroute.v")
    _require_nonempty_directory(run_dir / "database")
    return slacks


def _write_exclusive(path: Path, payload: bytes) -> None:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(path, flags, 0o644)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
    finally:
        os.close(descriptor)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--top", required=True)
    parser.add_argument("--write-clean-marker", action="store_true")
    args = parser.parse_args(argv)
    try:
        slacks = validate(args.run_dir.resolve(), args.top)
        if args.write_clean_marker:
            _write_exclusive(args.run_dir / "status" / "FLOW_CLEAN", CLEAN_SENTINEL)
    except (OSError, QualificationError) as exc:
        print(f"W2_INNOVUS_NOT_CLEAN: {exc}", file=sys.stderr)
        return 2
    values = " ".join(f"{name}_wns={value:g}" for name, value in sorted(slacks.items()))
    print(f"W2_INNOVUS_FLOW_CLEAN {values}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
