#!/usr/bin/env python3
"""Mutation-heavy gates for producer-bound single-edge power evidence."""

from __future__ import annotations

import copy
import hashlib
import hmac
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[2]
FLOW = ROOT / "physical/k2_single_edge_vectorless/preflight.py"
SPEC = importlib.util.spec_from_file_location("k2_single_edge_vectorless", FLOW)
assert SPEC and SPEC.loader
flow = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(flow)


def power_report(top: str, *, activity: str = "N.A.", user: str = "N.A.",
                 sequential: str = "0.200000", primary: str = "0.200000") -> bytes:
    return f"""Generated by:           Genus(TM) Synthesis Solution
Instance: /{top}
* User-Defined Activity : {user}
* Activity File: {activity}
* Sequential Element Activity: {sequential}
* Primary Input Activity: {primary}
Power Unit: W
    Category         Leakage     Internal    Switching        Total
    Subtotal     1.00000e-09  1.00000e-06  1.00000e-06  2.00100e-06
""".encode()


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(flow.canonical(value))


def contract_and_sources() -> tuple[dict, dict]:
    contract, _ = flow.load_contract(ROOT)
    sources = flow.validate_contract(ROOT, contract)
    return contract, sources


def receipt_shell(schema: str, contract: dict, candidate: str,
                  *, synthetic: bool = False, inherited: bool = False,
                  p6: bool = False) -> dict:
    design = contract["candidates"][candidate]
    return {
        "schema": schema,
        "status": "PRODUCER_COMPLETE",
        "evidence_class": contract["evidence_class"],
        "candidate": candidate,
        "architecture": design["architecture"],
        "interface": "SINGLE_EDGE_PARALLEL",
        "boundary": design["boundary"],
        "lineage": {"synthetic": synthetic, "inherited": inherited,
                    "p6": p6, "borrowed_dependency_ids": []},
        "top": design["top"],
        "producer": {},
        "operating_point": contract["operating_point"],
        "activity_policy": contract["activity_policy"],
        "tool": contract["tool"],
        "execution": {},
        "artifacts": {},
        "complete_artifact_ledger_sha256": "0" * 64,
        "attestation": {},
    }


class ContractAndTemplateTest(unittest.TestCase):
    def test_exact_commit_top_filelist_and_source_pins(self) -> None:
        contract, sources = contract_and_sources()
        self.assertEqual(sources["producer_commit"],
                         "4ce4836fab1309d3468db8e660d2da9af371f784")
        self.assertEqual(contract["decision_policy"]["candidate_order"],
                         ["a2_single_edge", "a3_single_edge"])
        self.assertEqual(
            [contract["candidates"][key]["top"] for key in
             contract["decision_policy"]["candidate_order"]],
            ["a2_batched_iwrr_single_edge_top",
             "a3_exact_scalar_prefix_k2_single_edge_top"])
        for key, row in sources["candidates"].items():
            self.assertEqual(len(row["filelists"]), 2, key)
            self.assertEqual(len(row["sources"]), 5, key)
            for identity in row["filelists"] + row["sources"]:
                self.assertNotIn("p6", identity["path"].lower())
                self.assertRegex(identity["sha256"], r"^[0-9a-f]{64}$")

    def test_complete_boundary_ports_are_not_raw_or_normalized_guesses(self) -> None:
        contract, _ = contract_and_sources()
        for key, row in contract["candidates"].items():
            self.assertEqual(row["boundary"],
                             "SOURCE_PENDING_ACCEPT_THROUGH_SINGLE_EDGE_LINK_RETIRE")
            self.assertIn("source_pending_i[15:0]", row["inputs"])
            self.assertIn("source_accept_o[15:0]", row["outputs"])
            self.assertIn("protocol_error_o", row["outputs"])
            self.assertIn("drain_idle_o", row["outputs"])
            self.assertNotIn("normalized", row["top"], key)

    def test_driver_is_mapped_and_has_no_activity_override(self) -> None:
        contract, _ = contract_and_sources()
        driver = (ROOT / contract["templates"]["driver"]["path"]).read_bytes()
        lowered = driver.lower()
        for token in contract["activity_policy"]["forbidden_tokens"]:
            self.assertNotIn(token.encode(), lowered)
        for command in (b"syn_generic", b"syn_map", b"syn_opt", b"write_hdl",
                        b"write_sdc", b"write_sdf"):
            self.assertEqual(lowered.count(command), 1)
        self.assertEqual(lowered.count(b"report_power"), 1)

    def test_exact_sdc_corner_clock_io_and_load(self) -> None:
        contract, _ = contract_and_sources()
        point = contract["operating_point"]
        self.assertEqual(point["corner"], {
            "pdk": "GPDK045/gsclib045", "process": 1.0,
            "voltage_v": 0.9, "temperature_c": 125.0,
            "power_liberty_role": "setup_slow"})
        self.assertEqual(point["clock"]["port"], "clk_i")
        self.assertEqual(point["clock"]["period_ns"], 6.5)
        self.assertEqual(point["clock"]["waveform_ns"], [0.0, 3.25])
        self.assertEqual(point["io"]["input_delay_min_ns"], 0.1)
        self.assertEqual(point["io"]["input_delay_max_ns"], 0.5)
        self.assertEqual(point["load"]["all_outputs_pf"], 0.01)
        sdc = (ROOT / contract["templates"]["sdc"]["path"]).read_text().lower()
        self.assertIn("[get_ports clk_i]", sdc)
        self.assertNotRegex(sdc, r"\b(false_path|multicycle|p6|negedge|falling)\b")

    def test_receipt_template_is_explicit_non_evidence_hold(self) -> None:
        template = json.loads((ROOT /
            "physical/k2_single_edge_vectorless/producer-receipt.template.json").read_text())
        self.assertEqual(template["status"], "HOLD_TEMPLATE_NOT_EXECUTION_EVIDENCE")
        self.assertFalse(template["candidate_go"])
        for field in ("mapped_netlist_sha256", "materialized_sdc_sha256",
                      "genus_log_sha256", "exact_executed_argv", "genus_exit_code",
                      "complete_artifact_ledger_sha256", "producer_attestation"):
            self.assertIsNone(template[field])

    def test_operating_tool_activity_and_policy_mutations_fail(self) -> None:
        good, _ = flow.load_contract(ROOT)
        mutations = []
        period = copy.deepcopy(good)
        period["operating_point"]["clock"]["period_ns"] = 5.7
        mutations.append(period)
        waveform = copy.deepcopy(good)
        waveform["operating_point"]["clock"]["waveform_ns"] = [0.0, 2.85]
        mutations.append(waveform)
        corner = copy.deepcopy(good)
        corner["operating_point"]["corner"]["voltage_v"] = 1.0
        mutations.append(corner)
        delay = copy.deepcopy(good)
        delay["operating_point"]["io"]["input_delay_max_ns"] = 0.6
        mutations.append(delay)
        load = copy.deepcopy(good)
        load["operating_point"]["load"]["all_outputs_pf"] = 0.02
        mutations.append(load)
        tool = copy.deepcopy(good)
        tool["tool"]["version"] = "caller-says-genus"
        mutations.append(tool)
        activity = copy.deepcopy(good)
        activity["activity_policy"]["per_object_activity_allowed"] = True
        mutations.append(activity)
        p6 = copy.deepcopy(good)
        p6["decision_policy"]["p6_allowed"] = True
        mutations.append(p6)
        unknown = copy.deepcopy(good)
        unknown["caller_go"] = True
        mutations.append(unknown)
        for index, mutation in enumerate(mutations):
            with self.subTest(index=index), self.assertRaises(flow.EvidenceError):
                flow.validate_contract(ROOT, mutation)


class PreflightTest(unittest.TestCase):
    def test_preflight_is_eda_free_honest_hold(self) -> None:
        real_run = subprocess.run
        calls: list[list[str]] = []

        def git_only(argv, *args, **kwargs):
            calls.append(list(argv))
            self.assertEqual(argv[0], "git")
            return real_run(argv, *args, **kwargs)

        with tempfile.TemporaryDirectory() as temporary, mock.patch.object(
                flow.subprocess, "run", side_effect=git_only):
            output = Path(temporary) / "preflight.json"
            flow.preflight(ROOT, output)
            result = json.loads(output.read_text())
        self.assertTrue(calls)
        self.assertEqual(result["status"],
                         "HOLD_NO_PRODUCER_BOUND_SERVER_ARTIFACTS")
        self.assertFalse(result["candidate_go"])
        self.assertFalse(result["comparison_ready"])
        self.assertFalse(result["activity_annotated"])
        self.assertEqual(result["power_method"],
                         "GENUS_MAPPED_DEFAULT_VECTORLESS")

    def test_preflight_output_is_create_exclusive(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "preflight.json"
            flow.preflight(ROOT, output)
            with self.assertRaisesRegex(flow.EvidenceError, "immutable output"):
                flow.preflight(ROOT, output)

    def test_cli_reports_hold_not_pass_or_go(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "preflight.json"
            completed = subprocess.run(
                ["python3", str(FLOW), "preflight", "--repo-root", str(ROOT),
                 "--output", str(output)], text=True, capture_output=True,
                check=False)
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("K2_SINGLE_EDGE_VECTORLESS_HOLD", completed.stdout)
            self.assertNotIn("_GO", completed.stdout)
            self.assertNotIn("_PASS", completed.stdout)


class ActivityAndPowerTest(unittest.TestCase):
    TOP = "a2_batched_iwrr_single_edge_top"

    @classmethod
    def setUpClass(cls) -> None:
        cls.contract, _ = contract_and_sources()
        cls.activity = cls.contract["activity_policy"]

    def test_exact_native_default_vectorless_report_parses(self) -> None:
        result = flow.parse_power_report(power_report(self.TOP), self.TOP,
                                         self.activity)
        self.assertAlmostEqual(result["total_mw"], 0.002001)
        self.assertAlmostEqual(result["leakage_mw"], 0.000001)

    def test_imported_or_user_activity_and_default_mutations_fail(self) -> None:
        mutations = (
            power_report(self.TOP, activity="N/A"),
            power_report(self.TOP, activity="run.vcd"),
            power_report(self.TOP, activity="run.saif"),
            power_report(self.TOP, user="Imported"),
            power_report(self.TOP, sequential="0.100000"),
            power_report(self.TOP, primary="0.300000"),
        )
        for payload in mutations:
            with self.subTest(payload=payload), self.assertRaises(flow.EvidenceError):
                flow.parse_power_report(payload, self.TOP, self.activity)

    def test_missing_duplicate_wrong_top_unit_and_sum_fail(self) -> None:
        valid = power_report(self.TOP)
        mutations = (
            valid.replace(b"* Activity File: N.A.\n", b""),
            valid + b"* Activity File: N.A.\n",
            valid.replace(self.TOP.encode(), b"wrong_top"),
            valid.replace(b"Power Unit: W", b"Power Unit: mW"),
            valid.replace(b"2.00100e-06", b"9.00000e-06"),
        )
        for payload in mutations:
            with self.subTest(payload=payload), self.assertRaises(flow.EvidenceError):
                flow.parse_power_report(payload, self.TOP, self.activity)

    def test_case_variant_activity_commands_fail_every_text_surface(self) -> None:
        for token in (b"READ_VCD run", b"Read_Saif run", b"read_tcf run",
                      b"set_switching_activity x", b"LP_TOGGLE_RATE 0.1",
                      b"lp_static_probability 0.5", b"set_power_activity x",
                      b"set_activity x", b"toggle_rate=0.4"):
            with self.subTest(token=token), self.assertRaises(flow.EvidenceError):
                flow.reject_activity(token, "mutated command", self.activity["forbidden_tokens"])

    def test_log_requires_real_completion_shape_and_forbids_activity(self) -> None:
        valid = (f"Version: {self.contract['tool']['version']}\n"
                 f"K2_SINGLE_EDGE_VECTORLESS_PRODUCER_PASS top={self.TOP}\n"
                 "Info=10, Warn=2, Error=0, Fatal=0\nNormal exit.\n").encode()
        flow.verify_genus_log(valid, self.TOP, self.contract)
        for payload in (valid.replace(b"Normal exit.\n", b""),
                        valid.replace(b"Error=0", b"Error=1"),
                        valid + b"set_switching_activity x\n"):
            with self.assertRaises(flow.EvidenceError):
                flow.verify_genus_log(payload, self.TOP, self.contract)


class ProvenanceAndFilesystemTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.contract, cls.sources = contract_and_sources()

    def _write_receipt(self, attempt: Path, receipt: dict) -> None:
        write_json(attempt / "producer-receipt.json", receipt)

    def test_legacy_inherited_and_p6_receipt_schemas_fail_before_hashes(self) -> None:
        schemas = (
            "k2_w2_genus_exact_three_endpoint_receipt_v3",
            "k2_endpoint_vectorless_evidence_v2",
            "a2_p6_caller_rehashed_receipt_v99",
            "k2_single_edge_vectorless_producer_receipt_template_v1",
            "synthetic_real_server_receipt_v1",
        )
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            for schema in schemas:
                with self.subTest(schema=schema):
                    receipt = receipt_shell(schema, self.contract, "a2_single_edge")
                    self._write_receipt(attempt, receipt)
                    with self.assertRaisesRegex(flow.EvidenceError,
                                                "legacy|unsupported"):
                        flow.verify_attempt(
                            attempt, "a2_single_edge",
                            self.contract["candidates"]["a2_single_edge"]["top"],
                            self.sources, self.contract)

    def test_explicit_synthetic_inherited_and_p6_lineage_fail(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            for field in ("synthetic", "inherited", "p6"):
                options = {"synthetic": False, "inherited": False, "p6": False}
                options[field] = True
                receipt = receipt_shell(
                    self.contract["producer_authority"]["accepted_receipt_schema"],
                    self.contract, "a2_single_edge", **options)
                self._write_receipt(attempt, receipt)
                with self.subTest(field=field), self.assertRaisesRegex(
                        flow.EvidenceError, "synthetic/inherited/P6"):
                    flow.verify_attempt(
                        attempt, "a2_single_edge",
                        self.contract["candidates"]["a2_single_edge"]["top"],
                        self.sources, self.contract)

    def test_caller_go_and_unknown_receipt_field_fail(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            receipt = receipt_shell(
                self.contract["producer_authority"]["accepted_receipt_schema"],
                self.contract, "a2_single_edge")
            receipt["candidate_go"] = True
            self._write_receipt(attempt, receipt)
            with self.assertRaisesRegex(flow.EvidenceError, "keys mismatch"):
                flow.verify_attempt(
                    attempt, "a2_single_edge",
                    self.contract["candidates"]["a2_single_edge"]["top"],
                    self.sources, self.contract)

    def test_artifact_byte_hash_size_path_symlink_and_hardlink_mutations_fail(self) -> None:
        mini_contract = {"artifact_policy": {
            "fixed_roles": ["blob"], "source_role_prefix": "source_",
            "filelist_role_prefix": "filelist_"}}
        mini_sources = {"candidates": {"a2_single_edge": {
            "sources": [], "filelists": []}}}
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            blob = attempt / "blob.bin"
            blob.write_bytes(b"actual mapped artifact\n")
            row = {"path": "blob.bin", "sha256": flow.sha256(blob.read_bytes()),
                   "size_bytes": blob.stat().st_size}
            receipt = {"artifacts": {"blob": row}}
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            payloads, _ = flow._artifact_rows(
                attempt, receipt, "a2_single_edge", mini_sources, mini_contract)
            self.assertEqual(payloads["blob"], blob.read_bytes())

            blob.write_bytes(b"mutated\n")
            with self.assertRaisesRegex(flow.EvidenceError, "bytes/hash/size"):
                flow._artifact_rows(
                    attempt, receipt, "a2_single_edge", mini_sources, mini_contract)
            blob.write_bytes(b"actual mapped artifact\n")

            receipt["artifacts"]["blob"]["path"] = "../escape"
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            with self.assertRaisesRegex(flow.EvidenceError, "normalized"):
                flow._artifact_rows(
                    attempt, receipt, "a2_single_edge", mini_sources, mini_contract)

            link = attempt / "link.bin"
            link.symlink_to(blob)
            receipt["artifacts"]["blob"] = {
                "path": "link.bin", "sha256": flow.sha256(blob.read_bytes()),
                "size_bytes": blob.stat().st_size}
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            with self.assertRaises(flow.EvidenceError):
                flow._artifact_rows(
                    attempt, receipt, "a2_single_edge", mini_sources, mini_contract)

            link.unlink()
            os.link(blob, link)
            with self.assertRaisesRegex(flow.EvidenceError, "single-link"):
                flow._artifact_rows(
                    attempt, receipt, "a2_single_edge", mini_sources, mini_contract)

    def test_every_netlist_sdc_lib_command_environment_log_and_report_is_bound(self) -> None:
        roles = self.contract["artifact_policy"]["fixed_roles"]
        mini_contract = {"artifact_policy": {
            "fixed_roles": roles, "source_role_prefix": "source_",
            "filelist_role_prefix": "filelist_"}}
        mini_sources = {"candidates": {"a2_single_edge": {
            "sources": [], "filelists": []}}}
        expected = {
            "source_manifest", "driver_tcl", "input_sdc", "materialized_sdc",
            "mapped_sdc", "setup_liberty", "hold_liberty", "mapped_netlist",
            "mapped_sdf", "genus_log", "report_area", "report_timing",
            "report_power", "report_qor", "report_timing_intent",
            "report_clocks", "environment_receipt", "command_receipt",
        }
        self.assertEqual(set(roles), expected)
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            artifacts = {}
            for role in roles:
                payload = f"producer bytes for {role}\n".encode()
                path = attempt / f"{role}.bin"
                path.write_bytes(payload)
                artifacts[role] = {"path": path.name,
                                   "sha256": flow.sha256(payload),
                                   "size_bytes": len(payload)}
            receipt = {"artifacts": artifacts,
                       "complete_artifact_ledger_sha256":
                           flow.sha256(flow.canonical(artifacts))}
            flow._artifact_rows(
                attempt, receipt, "a2_single_edge", mini_sources, mini_contract)
            for role in roles:
                path = attempt / artifacts[role]["path"]
                original = path.read_bytes()
                path.write_bytes(original + b"caller mutation\n")
                with self.subTest(role=role), self.assertRaisesRegex(
                        flow.EvidenceError, "bytes/hash/size"):
                    flow._artifact_rows(
                        attempt, receipt, "a2_single_edge", mini_sources,
                        mini_contract)
                path.write_bytes(original)

    def test_artifact_names_with_forbidden_lineage_fail(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for name in ("borrowed_p6.rpt", "synthetic.rpt", "inherited.rpt",
                         "waves.vcd", "waves.saif"):
                (root / name).write_text("x")
                with self.subTest(name=name), self.assertRaises(flow.EvidenceError):
                    flow.read_beneath(root, name, "artifact")

    def test_duplicate_json_keys_and_nonfinite_values_fail(self) -> None:
        with self.assertRaisesRegex(flow.EvidenceError, "duplicate JSON key"):
            flow.parse_json(b'{"x":1,"x":2}', "duplicate")
        with self.assertRaisesRegex(flow.EvidenceError, "non-finite"):
            flow.parse_json(b'{"x":NaN}', "nan")


class QualificationDecisionTest(unittest.TestCase):
    def test_attestation_mac_covers_complete_receipt_payload(self) -> None:
        secret = bytes(range(32))
        unsigned = {"schema": "test", "complete_artifact_ledger_sha256": "a" * 64}
        mac = hmac.new(secret, flow.canonical(unsigned), hashlib.sha256).hexdigest()
        receipt = {**unsigned, "attestation": {"key_id": "producer", "mac_sha256": mac}}
        row = {"candidate": "a2_single_edge", "receipt": receipt}
        flow._authenticate(row, {"producer": secret})
        receipt["complete_artifact_ledger_sha256"] = "b" * 64
        with self.assertRaisesRegex(flow.EvidenceError, "MAC mismatch"):
            flow._authenticate(row, {"producer": secret})

    def test_verified_looking_local_rows_without_keyring_can_only_hold(self) -> None:
        contract, contract_payload = flow.load_contract(ROOT)
        order = contract["decision_policy"]["candidate_order"]
        with tempfile.TemporaryDirectory() as temporary:
            evidence_root = Path(temporary)
            for name in ("a2", "a3"):
                (evidence_root / name).mkdir()
            evidence = {
                "schema": "k2_single_edge_vectorless_evidence_v1",
                "evidence_class": contract["evidence_class"],
                "candidate_order": order,
                "interface": "SINGLE_EDGE_PARALLEL",
                "contract_sha256": flow.sha256(contract_payload),
                "rows": [
                    {"candidate": key, "top": contract["candidates"][key]["top"],
                     "attempt_directory": "a2" if index == 0 else "a3"}
                    for index, key in enumerate(order)
                ],
            }
            evidence_path = evidence_root / "vectorless-evidence.json"
            write_json(evidence_path, evidence)
            output = evidence_root / "qualification.json"
            fake_rows = [{
                "candidate": key, "top": contract["candidates"][key]["top"],
                "receipt": {}, "receipt_sha256": str(index + 1) * 64,
                "power": {"total_mw": 1.0}, "authority_id": "fake-label",
                "host_fingerprint_sha256": "a" * 64,
                "run_id": f"run-{index}", "artifact_ledger_sha256": "b" * 64,
            } for index, key in enumerate(order)]
            with mock.patch.object(flow, "verify_attempt", side_effect=fake_rows):
                flow.qualify(evidence_path, output)
            result = json.loads(output.read_text())
            self.assertEqual(result["status"],
                             "HOLD_UNAUTHENTICATED_PRODUCER_ARTIFACTS")
            self.assertFalse(result["producer_authenticated"])
            self.assertFalse(result["candidate_go"])
            self.assertFalse(result["comparison_ready"])

    def test_legacy_index_and_caller_go_fail_without_output(self) -> None:
        contract, contract_payload = flow.load_contract(ROOT)
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            evidence = {
                "schema": "k2_endpoint_vectorless_evidence_v2",
                "evidence_class": contract["evidence_class"],
                "candidate_order": contract["decision_policy"]["candidate_order"],
                "interface": "SINGLE_EDGE_PARALLEL",
                "contract_sha256": flow.sha256(contract_payload),
                "rows": [],
            }
            evidence_path = root / "evidence.json"
            output = root / "qualification.json"
            write_json(evidence_path, evidence)
            with self.assertRaisesRegex(flow.EvidenceError, "legacy"):
                flow.qualify(evidence_path, output)
            self.assertFalse(output.exists())

            evidence["schema"] = "k2_single_edge_vectorless_evidence_v1"
            evidence["candidate_go"] = True
            write_json(evidence_path, evidence)
            with self.assertRaisesRegex(flow.EvidenceError, "keys mismatch"):
                flow.qualify(evidence_path, output)
            self.assertFalse(output.exists())

    def test_keyring_path_and_out_of_band_hash_are_indivisible(self) -> None:
        contract, contract_payload = flow.load_contract(ROOT)
        order = contract["decision_policy"]["candidate_order"]
        with tempfile.TemporaryDirectory() as temporary:
            evidence_root = Path(temporary)
            for name in ("a2", "a3"):
                (evidence_root / name).mkdir()
            evidence = {
                "schema": "k2_single_edge_vectorless_evidence_v1",
                "evidence_class": contract["evidence_class"],
                "candidate_order": order, "interface": "SINGLE_EDGE_PARALLEL",
                "contract_sha256": flow.sha256(contract_payload),
                "rows": [{"candidate": key,
                          "top": contract["candidates"][key]["top"],
                          "attempt_directory": "a2" if index == 0 else "a3"}
                         for index, key in enumerate(order)],
            }
            evidence_path = evidence_root / "evidence.json"
            write_json(evidence_path, evidence)
            fake_rows = [{
                "candidate": key, "top": contract["candidates"][key]["top"],
                "receipt": {}, "receipt_sha256": str(index + 1) * 64,
                "power": {}, "authority_id": "authority",
                "host_fingerprint_sha256": "a" * 64,
                "run_id": f"run-{index}", "artifact_ledger_sha256": "b" * 64,
            } for index, key in enumerate(order)]
            with mock.patch.object(flow, "verify_attempt", side_effect=fake_rows):
                with self.assertRaisesRegex(flow.EvidenceError, "both required"):
                    flow.qualify(evidence_path, evidence_root / "out.json",
                                 keyring_path=Path("/secure/keyring"))


if __name__ == "__main__":
    unittest.main()
