#!/usr/bin/env python3
"""Adversarial gates for HOLD-only single-edge vectorless diagnostics."""

from __future__ import annotations

import copy
from contextlib import redirect_stdout
import importlib.util
import io
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[2]
FLOW = ROOT / "physical/k2_single_edge_vectorless/preflight.py"
SPEC = importlib.util.spec_from_file_location("k2_single_edge_vectorless", FLOW)
assert SPEC and SPEC.loader
flow = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(flow)


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(flow.canonical(value))


def contract_and_sources() -> tuple[dict, dict]:
    contract, _ = flow.load_contract(ROOT)
    return contract, flow.validate_contract(ROOT, contract)


def power_report(top: str) -> bytes:
    return f"""Generated by:           Genus(TM) Synthesis Solution
Instance: /{top}
* User-Defined Activity : N.A.
* Activity File: N.A.
* Sequential Element Activity: 0.200000
* Primary Input Activity: 0.200000
Power Unit: W
    Category         Leakage     Internal    Switching        Total
    Subtotal     1.00000e-09  1.00000e-06  1.00000e-06  2.00100e-06
""".encode()


def mapped_sdc() -> bytes:
    return b"""create_clock -name single_edge_clk -period 6.500 -waveform {0.000 3.250} [get_ports clk_i]
set_clock_uncertainty 0.250 [get_clocks single_edge_clk]
set_input_delay -clock single_edge_clk -min 0.100 [get_ports rst_i]
set_input_delay -clock single_edge_clk -max 0.500 [get_ports rst_i]
set_input_transition 0.050 [get_ports rst_i]
set_output_delay -clock single_edge_clk -min 0.100 [all_outputs]
set_output_delay -clock single_edge_clk -max 0.500 [all_outputs]
set_load 0.010 [all_outputs]
set_min_pulse_width -high 0.500 [get_clocks single_edge_clk]
set_min_pulse_width -low 0.500 [get_clocks single_edge_clk]
"""


def structural_netlist(top: str) -> bytes:
    inputs = "\n".join((
        "input clk_i;", "input rst_i;", "input link_enable_i;",
        "input [15:0] source_pending_i;",
    ))
    outputs = "\n".join((
        "output [15:0] source_accept_o;", "output [1:0] accept_count_o;",
        "output [3:0] accept_addr0_o;", "output [3:0] accept_addr1_o;",
        "output link_valid_o;", "output [3:0] link_addr0_o;",
        "output [3:0] link_addr1_o;", "output [1:0] retire_valid_o;",
        "output [3:0] retire_addr0_o;", "output [3:0] retire_addr1_o;",
        "output protocol_error_o;", "output drain_idle_o;",
    ))
    return f"""module {top} (clk_i, rst_i, link_enable_i, source_pending_i,
source_accept_o, accept_count_o, accept_addr0_o, accept_addr1_o, link_valid_o,
link_addr0_o, link_addr1_o, retire_valid_o, retire_addr0_o, retire_addr1_o,
protocol_error_o, drain_idle_o);
{inputs}
{outputs}
DFFX1 state_q (.D(link_enable_i), .CK(clk_i), .Q(link_valid_o));
endmodule
""".encode()


def diagnostic_index(root: Path, contract: dict, contract_payload: bytes) -> Path:
    for name in ("a2", "a3"):
        (root / name).mkdir()
    order = contract["decision_policy"]["candidate_order"]
    document = {
        "schema": "k2_single_edge_vectorless_diagnostic_index_v2",
        "evidence_class": contract["evidence_class"],
        "candidate_order": order,
        "interface": "SINGLE_EDGE_PARALLEL",
        "contract_sha256": flow.sha256(contract_payload),
        "rows": [
            {"candidate": candidate, "top": contract["candidates"][candidate]["top"],
             "attempt_directory": "a2" if index == 0 else "a3"}
            for index, candidate in enumerate(order)
        ],
    }
    path = root / "diagnostic-index.json"
    write_json(path, document)
    return path


def fake_diagnostic_rows(contract: dict) -> list[dict]:
    rows = []
    for index, candidate in enumerate(contract["decision_policy"]["candidate_order"]):
        rows.append({
            "candidate": candidate, "top": contract["candidates"][candidate]["top"],
            "receipt": {"fabricated": True}, "receipt_sha256": str(index + 1) * 64,
            "power": {"total_mw": 1.0}, "capture_id": f"fabricated-{index}",
            "claimed_host_fingerprint_sha256": "a" * 64,
            "artifact_ledger_sha256": "b" * 64,
            "structural_diagnostic": {"structural_instance_count": 1},
        })
    return rows


class ContractTest(unittest.TestCase):
    def test_hardened_commits_exact_filelists_sources_and_error_latch(self) -> None:
        contract, sources = contract_and_sources()
        self.assertEqual(sources["equivalent_hardened_commits"], [
            "a0a4eb38632245db8ff5937ea5b6c6e3f3839246",
            "6fc5e167918fa4c54786c9a3abb5f60ecd8b991b",
        ])
        for candidate, row in sources["candidates"].items():
            self.assertEqual(len(row["filelists"]), 2, candidate)
            self.assertEqual(len(row["sources"]), 6, candidate)
            self.assertIn("rtl/technology/single_edge/w2_single_edge_error_latch.sv",
                          [source["path"] for source in row["sources"]])
        self.assertFalse(contract["decision_policy"]["candidate_go_possible"])
        self.assertFalse(contract["decision_policy"]["comparison_ready_possible"])

    def test_complete_boundary_port_sets_are_exact(self) -> None:
        contract, _ = contract_and_sources()
        for row in contract["candidates"].values():
            self.assertEqual(row["inputs"], flow.EXPECTED_INPUTS)
            self.assertEqual(row["outputs"], flow.EXPECTED_OUTPUTS)
        for mutate in ("drop", "add", "reorder"):
            changed = copy.deepcopy(contract)
            ports = changed["candidates"]["a2_single_edge"]["outputs"]
            if mutate == "drop":
                ports.pop()
            elif mutate == "add":
                ports.append("invented_o")
            else:
                ports.reverse()
            with self.subTest(mutate=mutate), self.assertRaises(flow.EvidenceError):
                flow.validate_contract(ROOT, changed)

    def test_placeholder_and_no_controlled_producer_are_immutable(self) -> None:
        contract, _ = contract_and_sources()
        expected = {
            "status": "UNCONFIRMED_TEAM_PLACEHOLDER",
            "evidence_class": "TEAM_PLACEHOLDER_SCREENING_ONLY",
            "external_authority_available": False,
            "values_are_release_claims": False,
            "candidate_go_eligible": False,
            "comparison_ready_eligible": False,
            "maximum_status": flow.HOLD_STATUS,
        }
        self.assertEqual(contract["constraint_authority"], expected)
        provenance = contract["diagnostic_provenance"]
        for field in ("controlled_runner_available", "live_host_binding_available",
                      "freshness_or_replay_protection_available",
                      "keyring_or_hmac_accepted", "structural_validation_implies_equivalence",
                      "structural_validation_implies_signoff"):
            self.assertIs(provenance[field], False, field)
        for field, value in (("candidate_go_eligible", True),
                             ("comparison_ready_eligible", True),
                             ("external_authority_available", True)):
            changed = copy.deepcopy(contract)
            changed["constraint_authority"][field] = value
            with self.subTest(field=field), self.assertRaises(flow.EvidenceError):
                flow.validate_contract(ROOT, changed)

    def test_driver_and_sdc_are_default_vectorless_placeholder_only(self) -> None:
        contract, _ = contract_and_sources()
        driver = (ROOT / contract["templates"]["driver"]["path"]).read_text()
        self.assertIn("K2_SE_ACTIVITY_MODE", driver)
        self.assertIn("GENUS_DEFAULT_VECTORLESS", driver)
        self.assertIn("check_design -all", driver)
        self.assertEqual(driver.count("report_power"), 1)
        for token in contract["activity_policy"]["forbidden_tokens"]:
            self.assertNotIn(token, driver.lower())
        sdc = (ROOT / contract["templates"]["sdc"]["path"]).read_text()
        self.assertIn("UNCONFIRMED_TEAM_PLACEHOLDER", sdc)
        self.assertEqual(sdc.count("create_clock "), 1)
        self.assertNotIn("create_generated_clock", sdc)

    def test_template_is_explicit_diagnostic_hold(self) -> None:
        template = json.loads((ROOT /
            "physical/k2_single_edge_vectorless/diagnostic-receipt.template.json").read_text())
        self.assertEqual(template["maximum_status"], flow.HOLD_STATUS)
        self.assertFalse(template["candidate_go"])
        self.assertFalse(template["comparison_ready"])
        self.assertNotIn("producer_attestation", template)
        self.assertIn("NO_FRESHNESS_OR_REPLAY_PROTECTION", template["limitations"])


class HoldConstructionTest(unittest.TestCase):
    def test_preflight_api_and_cli_are_exact_hold(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            direct = root / "direct.json"
            flow.preflight(ROOT, direct)
            result = json.loads(direct.read_text())
            self.assertEqual(result["status"], flow.HOLD_STATUS)
            self.assertFalse(result["candidate_go"])
            self.assertFalse(result["comparison_ready"])
            cli = root / "cli.json"
            completed = subprocess.run(
                ["python3", str(FLOW), "preflight", "--repo-root", str(ROOT),
                 "--output", str(cli)], text=True, capture_output=True, check=False)
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("K2_SINGLE_EDGE_VECTORLESS_HOLD", completed.stdout)
            self.assertNotIn("_GO", completed.stdout)
            self.assertEqual(json.loads(cli.read_text())["status"], flow.HOLD_STATUS)

    def test_even_mocked_fabricated_complete_bundle_is_hold_api_and_cli(self) -> None:
        contract, payload = flow.load_contract(ROOT)
        flow.validate_contract(ROOT, contract)
        rows = fake_diagnostic_rows(contract)
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            evidence = diagnostic_index(root, contract, payload)
            direct = root / "direct.json"
            with mock.patch.object(flow, "validate_diagnostic_attempt", side_effect=rows):
                flow.qualify(evidence, direct)
            result = json.loads(direct.read_text())
            self.assertEqual(result["status"], flow.HOLD_STATUS)
            self.assertFalse(result["candidate_go"])
            self.assertFalse(result["comparison_ready"])
            self.assertFalse(result["controlled_producer_available"])
            self.assertFalse(result["live_host_bound"])
            self.assertFalse(result["freshness_or_replay_protected"])
            self.assertIn("diagnostic_rows", result)
            self.assertNotIn("verified_rows", result)

            cli = root / "cli.json"
            stdout = io.StringIO()
            with mock.patch.object(flow, "validate_diagnostic_attempt", side_effect=rows), \
                    redirect_stdout(stdout):
                return_code = flow.main([
                    "qualify", "--repo-root", str(ROOT), "--evidence", str(evidence),
                    "--output", str(cli),
                ])
            self.assertEqual(return_code, 0)
            self.assertIn("K2_SINGLE_EDGE_VECTORLESS_HOLD", stdout.getvalue())
            self.assertNotIn("_GO", stdout.getvalue())
            self.assertFalse(json.loads(cli.read_text())["candidate_go"])

    def test_caller_keyring_is_rejected_by_api_and_cli(self) -> None:
        with self.assertRaisesRegex(flow.EvidenceError, "keyrings/HMAC are unsupported"):
            flow.qualify(Path("missing"), Path("unused"), keyring_path=Path("caller.json"),
                         expected_keyring_sha256="0" * 64)
        completed = subprocess.run(
            ["python3", str(FLOW), "qualify", "--evidence", "missing",
             "--output", "unused", "--keyring", "caller.json",
             "--keyring-sha256", "0" * 64], text=True, capture_output=True,
            check=False)
        self.assertEqual(completed.returncode, 2)
        self.assertIn("unrecognized arguments", completed.stderr)

    def test_no_go_literal_or_authentication_implementation_remains(self) -> None:
        source = FLOW.read_text()
        self.assertNotIn('"candidate_go": True', source)
        self.assertNotIn('"comparison_ready": True', source)
        self.assertNotIn("def _load_keyring", source)
        self.assertNotIn("def _authenticate", source)
        self.assertNotIn("import hmac", source)
        self.assertNotIn("GO_PRODUCER_BOUND", source)

    def test_outputs_are_create_exclusive(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "hold.json"
            flow.preflight(ROOT, output)
            with self.assertRaisesRegex(flow.EvidenceError, "immutable output"):
                flow.preflight(ROOT, output)


class PowerParserTest(unittest.TestCase):
    TOP = "a2_batched_iwrr_single_edge_top"

    @classmethod
    def setUpClass(cls) -> None:
        cls.contract, _ = contract_and_sources()
        cls.activity = cls.contract["activity_policy"]

    def test_exact_native_report_parses_w_to_mw_and_sum(self) -> None:
        result = flow.parse_power_report(power_report(self.TOP), self.TOP, self.activity)
        self.assertAlmostEqual(result["total_mw"], 0.002001)
        self.assertAlmostEqual(result["leakage_mw"], 0.000001)

    def test_header_unit_tool_top_and_sum_mutations_fail(self) -> None:
        valid = power_report(self.TOP)
        mutations = {
            "headerless": valid.replace(
                b"    Category         Leakage     Internal    Switching        Total\n", b""),
            "wrong-order": valid.replace(b"Leakage     Internal    Switching",
                                          b"Internal    Leakage     Switching"),
            "duplicate-w": valid + b"Power Unit: W\n",
            "contradictory-unit": valid + b"Power Unit: mW\n",
            "wrong-tool": valid.replace(b"Genus(TM) Synthesis Solution", b"Not Genus"),
            "duplicate-tool": valid + b"Generated by: Genus(TM) Synthesis Solution\n",
            "wrong-top": valid.replace(self.TOP.encode(), b"wrong_top"),
            "duplicate-top": valid + f"Instance: /{self.TOP}\n".encode(),
            "bad-sum": valid.replace(b"2.00100e-06", b"9.00000e-06"),
            "missing-subtotal": valid.replace(b"    Subtotal", b"    NotTotal"),
        }
        for name, mutation in mutations.items():
            with self.subTest(name=name), self.assertRaises(flow.EvidenceError):
                flow.parse_power_report(mutation, self.TOP, self.activity)

    def test_activity_imports_defaults_and_commands_fail(self) -> None:
        valid = power_report(self.TOP)
        mutations = (
            valid.replace(b"Activity File: N.A.", b"Activity File: run.vcd"),
            valid.replace(b"User-Defined Activity : N.A.",
                          b"User-Defined Activity : Imported"),
            valid.replace(b"Sequential Element Activity: 0.200000",
                          b"Sequential Element Activity: 0.100000"),
            valid + b"SET_SWITCHING_ACTIVITY x\n",
        )
        for mutation in mutations:
            with self.assertRaises(flow.EvidenceError):
                flow.parse_power_report(mutation, self.TOP, self.activity)


class StructuralDiagnosticTest(unittest.TestCase):
    TOP = "a2_batched_iwrr_single_edge_top"

    def test_nonempty_complete_structural_netlist_is_diagnostic_only(self) -> None:
        result = flow.validate_structural_netlist(structural_netlist(self.TOP), self.TOP)
        self.assertGreater(result["structural_instance_count"], 0)

    def test_empty_incomplete_behavioral_and_extra_module_netlists_fail(self) -> None:
        valid = structural_netlist(self.TOP)
        mutations = (
            f"module {self.TOP}; endmodule\n".encode(),
            valid.replace(b"output drain_idle_o;\n", b""),
            valid.replace(b"DFFX1 state_q", b"always state_q"),
            valid + b"module extra; endmodule\n",
        )
        for mutation in mutations:
            with self.assertRaises(flow.EvidenceError):
                flow.validate_structural_netlist(mutation, self.TOP)

    def test_exact_mapped_sdc_and_adversarial_mutations(self) -> None:
        flow.validate_mapped_sdc(mapped_sdc())
        mutations = (
            b"# single_edge_clk 6.500\n",
            mapped_sdc() + b"create_clock -name second -period 9.000 [get_ports rst_i]\n",
            mapped_sdc() + b"create_generated_clock -name derived [get_ports rst_i]\n",
            mapped_sdc() + b"set_false_path -from [get_ports rst_i]\n",
            mapped_sdc().replace(b"set_load 0.010", b"set_load 0.020"),
            mapped_sdc().replace(b"-period 6.500", b"-period 5.000"),
        )
        for mutation in mutations:
            with self.assertRaises(flow.EvidenceError):
                flow.validate_mapped_sdc(mutation)

    def test_check_design_requires_nonempty_native_context(self) -> None:
        good = f"Genus check_design -all\nDesign: {self.TOP}\nNo unresolved references\n".encode()
        flow.validate_check_design_diagnostic(good, self.TOP)
        for mutation in (b"x\n", good.replace(self.TOP.encode(), b"wrong"),
                         good + b"unresolved references: 1\n", good + b"Error: bad\n"):
            with self.assertRaises(flow.EvidenceError):
                flow.validate_check_design_diagnostic(mutation, self.TOP)

    def test_log_requires_diagnostic_marker_not_pass_claim(self) -> None:
        contract, _ = contract_and_sources()
        good = (f"Version: {contract['tool']['version']}\n"
                f"K2_SINGLE_EDGE_VECTORLESS_DIAGNOSTIC_COMPLETE top={self.TOP}\n"
                "Info=10, Warn=2, Error=0, Fatal=0\nNormal exit.\n").encode()
        flow.validate_genus_diagnostic_log(good, self.TOP, contract)
        for mutation in (
                good.replace(b"DIAGNOSTIC_COMPLETE", b"PRODUCER_PASS"),
                good.replace(b"Normal exit.\n", b""),
                good.replace(b"Error=0", b"Error=1"),
                good + b"read_saif run.saif\n"):
            with self.assertRaises(flow.EvidenceError):
                flow.validate_genus_diagnostic_log(mutation, self.TOP, contract)


class FilesystemAndSchemaTest(unittest.TestCase):
    def test_complete_artifact_roles_include_connectivity_diagnostic(self) -> None:
        contract, _ = contract_and_sources()
        roles = contract["artifact_policy"]["fixed_roles"]
        self.assertEqual(len(roles), 19)
        self.assertIn("report_check_design", roles)
        self.assertIn("mapped_netlist", roles)
        self.assertIn("mapped_sdc", roles)
        self.assertIn("report_power", roles)

    def test_hash_size_traversal_symlink_and_hardlink_mutations_fail(self) -> None:
        mini_contract = {"artifact_policy": {
            "fixed_roles": ["blob"], "source_role_prefix": "source_",
            "filelist_role_prefix": "filelist_"}}
        mini_sources = {"candidates": {"a2_single_edge": {
            "sources": [], "filelists": []}}}
        with tempfile.TemporaryDirectory() as temporary:
            attempt = Path(temporary)
            blob = attempt / "blob.bin"
            blob.write_bytes(b"diagnostic bytes\n")
            row = {"path": "blob.bin", "sha256": flow.sha256(blob.read_bytes()),
                   "size_bytes": blob.stat().st_size}
            receipt = {"artifacts": {"blob": row}}
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            flow._artifact_rows(attempt, receipt, "a2_single_edge", mini_sources,
                                mini_contract)
            blob.write_bytes(b"changed\n")
            with self.assertRaises(flow.EvidenceError):
                flow._artifact_rows(attempt, receipt, "a2_single_edge", mini_sources,
                                    mini_contract)
            blob.write_bytes(b"diagnostic bytes\n")
            receipt["artifacts"]["blob"]["path"] = "../escape"
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            with self.assertRaises(flow.EvidenceError):
                flow._artifact_rows(attempt, receipt, "a2_single_edge", mini_sources,
                                    mini_contract)
            link = attempt / "link.bin"
            link.symlink_to(blob)
            receipt["artifacts"]["blob"] = {
                "path": "link.bin", "sha256": flow.sha256(blob.read_bytes()),
                "size_bytes": blob.stat().st_size}
            receipt["complete_artifact_ledger_sha256"] = flow.sha256(
                flow.canonical(receipt["artifacts"]))
            with self.assertRaises(flow.EvidenceError):
                flow._artifact_rows(attempt, receipt, "a2_single_edge", mini_sources,
                                    mini_contract)
            link.unlink()
            os.link(blob, link)
            with self.assertRaises(flow.EvidenceError):
                flow._artifact_rows(attempt, receipt, "a2_single_edge", mini_sources,
                                    mini_contract)

    def test_duplicate_json_nonfinite_and_caller_go_fail(self) -> None:
        with self.assertRaises(flow.EvidenceError):
            flow.parse_json(b'{"x":1,"x":2}', "duplicate")
        with self.assertRaises(flow.EvidenceError):
            flow.parse_json(b'{"x":NaN}', "nan")
        contract, payload = flow.load_contract(ROOT)
        with tempfile.TemporaryDirectory() as temporary:
            path = diagnostic_index(Path(temporary), contract, payload)
            document = json.loads(path.read_text())
            document["candidate_go"] = True
            write_json(path, document)
            with self.assertRaisesRegex(flow.EvidenceError, "keys mismatch"):
                flow.qualify(path, Path(temporary) / "out.json")


if __name__ == "__main__":
    unittest.main()
