# ####################################################################

#  Created by Genus(TM) Synthesis Solution 23.14-s090_1 on Mon Aug 24 09:17:37 KST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design aer_tx16_trad_rowcol_fovea_cluster2_steal_buf_polarity

create_clock -name "clk" -period 4.5 -waveform {0.0 2.25} [get_ports clk]
set_load -pin_load 0.01 [get_ports {overrun[15]}]
set_load -pin_load 0.01 [get_ports {overrun[14]}]
set_load -pin_load 0.01 [get_ports {overrun[13]}]
set_load -pin_load 0.01 [get_ports {overrun[12]}]
set_load -pin_load 0.01 [get_ports {overrun[11]}]
set_load -pin_load 0.01 [get_ports {overrun[10]}]
set_load -pin_load 0.01 [get_ports {overrun[9]}]
set_load -pin_load 0.01 [get_ports {overrun[8]}]
set_load -pin_load 0.01 [get_ports {overrun[7]}]
set_load -pin_load 0.01 [get_ports {overrun[6]}]
set_load -pin_load 0.01 [get_ports {overrun[5]}]
set_load -pin_load 0.01 [get_ports {overrun[4]}]
set_load -pin_load 0.01 [get_ports {overrun[3]}]
set_load -pin_load 0.01 [get_ports {overrun[2]}]
set_load -pin_load 0.01 [get_ports {overrun[1]}]
set_load -pin_load 0.01 [get_ports {overrun[0]}]
set_load -pin_load 0.01 [get_ports valid0]
set_load -pin_load 0.01 [get_ports {row0[1]}]
set_load -pin_load 0.01 [get_ports {row0[0]}]
set_load -pin_load 0.01 [get_ports {col_mask0[3]}]
set_load -pin_load 0.01 [get_ports {col_mask0[2]}]
set_load -pin_load 0.01 [get_ports {col_mask0[1]}]
set_load -pin_load 0.01 [get_ports {col_mask0[0]}]
set_load -pin_load 0.01 [get_ports {pol_mask0[3]}]
set_load -pin_load 0.01 [get_ports {pol_mask0[2]}]
set_load -pin_load 0.01 [get_ports {pol_mask0[1]}]
set_load -pin_load 0.01 [get_ports {pol_mask0[0]}]
set_load -pin_load 0.01 [get_ports valid1]
set_load -pin_load 0.01 [get_ports {row1[1]}]
set_load -pin_load 0.01 [get_ports {row1[0]}]
set_load -pin_load 0.01 [get_ports {col_mask1[3]}]
set_load -pin_load 0.01 [get_ports {col_mask1[2]}]
set_load -pin_load 0.01 [get_ports {col_mask1[1]}]
set_load -pin_load 0.01 [get_ports {col_mask1[0]}]
set_load -pin_load 0.01 [get_ports {pol_mask1[3]}]
set_load -pin_load 0.01 [get_ports {pol_mask1[2]}]
set_load -pin_load 0.01 [get_ports {pol_mask1[1]}]
set_load -pin_load 0.01 [get_ports {pol_mask1[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports rst]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {arrival[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {polarity_in[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {overrun[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports valid0]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {row0[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {row0[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask0[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask0[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask0[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask0[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask0[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask0[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask0[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask0[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports valid1]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {row1[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {row1[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask1[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask1[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask1[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {col_mask1[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask1[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask1[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask1[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.25 [get_ports {pol_mask1[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.1 [get_clocks clk]
set_clock_uncertainty -hold 0.1 [get_clocks clk]
